/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:04 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/AssistantUI.framework/AssistantUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Foundation/NSError.h>

@interface AFUIDebugError : NSError
+(id)debugErrorWithCode:(int)arg1 userInfo:(id)arg2 ;
-(id)initWithCode:(int)arg1 userInfo:(id)arg2 ;
@end

