/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:46:39 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/SafariServices.framework/SafariServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIButton.h>

@interface _SFDimmingButton : UIButton {

	float _normalImageAlpha;
	float _highlightedImageAlpha;
	double _highlightAnimationDuration;

}

@property (assign,nonatomic) float normalImageAlpha;                         //@synthesize normalImageAlpha=_normalImageAlpha - In the implementation block
@property (assign,nonatomic) float highlightedImageAlpha;                    //@synthesize highlightedImageAlpha=_highlightedImageAlpha - In the implementation block
@property (assign,nonatomic) double highlightAnimationDuration;              //@synthesize highlightAnimationDuration=_highlightAnimationDuration - In the implementation block
-(void)setNormalImageAlpha:(float)arg1 ;
-(void)setHighlightedImageAlpha:(float)arg1 ;
-(void)setHighlightAnimationDuration:(double)arg1 ;
-(void)_updateImageAlpha;
-(float)normalImageAlpha;
-(float)highlightedImageAlpha;
-(double)highlightAnimationDuration;
-(void)layoutSubviews;
-(void)setHighlighted:(char)arg1 ;
@end

