/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:46:39 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/SafariServices.framework/SafariServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/_UIBackdropView.h>

@class _SFNavigationBar;

@interface _SFNavigationBarBackdrop : _UIBackdropView {

	_SFNavigationBar* _navigationBar;

}

@property (assign,nonatomic) _SFNavigationBar * navigationBar;              //@synthesize navigationBar=_navigationBar - In the implementation block
-(_SFNavigationBar *)navigationBar;
-(void)setNavigationBar:(_SFNavigationBar *)arg1 ;
-(void)applySettings:(id)arg1 ;
@end

