/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:16:03 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/DuetPLLConfigLogger.framework/DuetPLLConfigLogger
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDate;

@interface fetchDenyEntry : NSObject {

	NSDate* _when;
	int _why;

}

@property (retain) NSDate * when;              //@synthesize when=_when - In the implementation block
@property (assign) int why;                    //@synthesize why=_why - In the implementation block
-(id)init;
-(NSDate *)when;
-(void)setWhen:(NSDate *)arg1 ;
-(int)why;
-(void)setWhy:(int)arg1 ;
@end

