/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:11 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/Message.framework/Message
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libobjc.A.dylib/MFDAMessagePayloadFetchResponse.h>

@class NSData;

@interface MFDAMessagePayloadFetchResponseImpl : NSObject <MFDAMessagePayloadFetchResponse> {

	char streaming;
	char streamingDone;
	NSData* data;

}
-(void)dealloc;
-(id)data;
-(char)streaming;
-(char)streamingDone;
-(id)initWithData:(id)arg1 streaming:(char)arg2 streamingDone:(char)arg3 ;
@end

