/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:16:58 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class IKCSSRuleList;

@interface IKCSSStylesheet : NSObject {

	IKCSSRuleList* _ruleList;

}

@property (nonatomic,retain) IKCSSRuleList * ruleList;              //@synthesize ruleList=_ruleList - In the implementation block
-(id)description;
-(IKCSSRuleList *)ruleList;
-(void)setRuleList:(IKCSSRuleList *)arg1 ;
@end

