/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:16:58 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class NSString;


@protocol IKJSDOMElement <JSExport>
@property (nonatomic,retain,readonly) NSString * tagName; 
@required
-(char)hasAttribute:(id)arg1;
-(void)removeAttribute:(id)arg1;
-(NSString *)tagName;
-(id)getAttribute:(id)arg1;
-(id)getElementsByTagName:(id)arg1;
-(void)setAttribute:(id)arg1 :(id)arg2;

@end

