/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:05 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/MapsSupport.framework/mapspushd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MapsPushDelegate <NSObject>
@required
-(void)pushManager:(id)arg1 receivedFixedProblemNotification:(id)arg2 manifestToken:(id)arg3;
-(void)pushManager:(id)arg1 gotPushData:(id)arg2;

@end

