/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:04 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/MapsSupport.framework/MapsSupport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MapsSupport/MSPFileContainerPersister.h>

@interface MSPFavoritesFileContainerPersister : MSPFileContainerPersister
-(id)dataForContents:(id)arg1 error:(out id*)arg2 ;
-(id)contentsFromData:(id)arg1 ;
@end

