/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:52 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol _UIBasicAnimationFactory <NSObject>
@optional
-(id)_timingFunctionForAnimation;
-(id)_timingFunctionForAnimationInView:(id)arg1 withKeyPath:(id)arg2;

@required
-(id)_basicAnimationForView:(id)arg1 withKeyPath:(id)arg2;

@end

