/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:57 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class UIView;

@interface SKUIOverlayFlipTransition : NSObject {

	UIView* _flipSourceView;

}

@property (nonatomic,retain) UIView * flipSourceView;              //@synthesize flipSourceView=_flipSourceView - In the implementation block
-(void)setFlipSourceView:(UIView *)arg1 ;
-(UIView *)flipSourceView;
@end

