/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:19:00 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface SKUISettingsFamilyViewStateCoordinator : NSObject {

	/*^block*/id _completionBlock;

}
-(void)checkSettingsFamilyViewStateWithBlock:(/*^block*/id)arg1 ;
-(void)_getSubscriptionStatus;
-(void)_checkSubscriptionStatus:(id)arg1 isFinal:(char)arg2 error:(id)arg3 ;
-(void)_returnFamilyViewState:(int)arg1 ;
@end

