/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:52 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SKUISlideshowViewControllerDelegate <NSObject>
@optional
-(id)slideshowViewController:(id)arg1 poppedImageViewAtIndex:(int)arg2;
-(void)slideshowViewController:(id)arg1 scrollToImageAtIndex:(int)arg2;
-(void)slideshowViewControllerDidFinish:(id)arg1;

@end

