/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:53 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SKUIScrollingSegmentedControllerDelegate <NSObject>
@optional
-(void)scrollingSegmentedController:(id)arg1 willDisplayViewControllerAtIndex:(unsigned)arg2;
-(void)scrollingSegmentedController:(id)arg1 didEndDisplayingViewControllerAtIndex:(unsigned)arg2;
-(void)scrollingSegmentedController:(id)arg1 didFocusViewControllerAtIndex:(unsigned)arg2;
-(void)scrollingSegmentedController:(id)arg1 contentScrollViewDidChangeForViewControllerAtIndex:(unsigned)arg2;

@end

