/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 4:45:49 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/CoreData.framework/CoreData
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreData/CoreData-Structs.h>
#import <CoreData/NSFetchRequest.h>

@class NSDictionary, NSHashTable;

@interface NSCachingFetchRequest : NSFetchRequest {

	NSDictionary* _substitutionVariables;
	NSHashTable* _cachingCoordinators;
	char _hasCachedInfo;
	id _identifier;

}

@property (nonatomic,copy) NSDictionary * substitutionVariables; 
@property (nonatomic,readonly) id _identifier;                                //@synthesize identifier=_identifier - In the implementation block
+(id)_generateIdentifier;
-(void)setSubstitutionVariables:(NSDictionary *)arg1 ;
-(id)_copyForDirtyContext;
-(NSDictionary *)substitutionVariables;
-(void)_registerCachingCoordinator:(id)arg1 ;
-(char)_hasRegisteredCachingCoordinator:(id)arg1 ;
-(void)_sanityCheckVariables:(id)arg1 ;
-(id)_identifier;
-(void)dealloc;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

