/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:03 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/Support/profiled
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

typedef struct {
	unsigned field1[8];
} SCD_Struct_MC0;

typedef struct __SecIdentity* SecIdentityRef;

typedef struct __SecCertificate* SecCertificateRef;

typedef struct __WiFiManagerClient* WiFiManagerClientRef;

typedef struct __WiFiNetwork* WiFiNetworkRef;

typedef struct __SCPreferences* SCPreferencesRef;

