/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:52:30 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/iAd.framework/iAd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ADPrerollTopBarDelegate <NSObject>
@required
-(void)topBarScaleToFill:(id)arg1;
-(void)topBarScaleToFit:(id)arg1;
-(void)topBarDoneButtonTapped:(id)arg1;

@end

