/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:42 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusOrigamiProducer.opplugin/OpusOrigamiProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <OpusOrigamiProducer/MCObjectLight.h>

@class NSString;

@interface MCAnimationPath : MCObjectLight {

	char mIsTriggered;
	char mIsSnapshot;
	NSString* mKey;

}

@property (copy) NSString * key; 
@property (assign,nonatomic) char isTriggered; 
+(id)animationPathWithKey:(id)arg1 ;
-(char)isSnapshot;
-(void)demolish;
-(id)initWithImprint:(id)arg1 ;
-(void)_copySelfToSnapshot:(id)arg1 ;
-(void)setIsTriggered:(char)arg1 ;
-(char)isTriggered;
-(NSString *)key;
-(void)setKey:(NSString *)arg1 ;
-(id)imprint;
@end

