/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:42 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusOrigamiProducer.opplugin/OpusOrigamiProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <OpusOrigamiProducer/MCAsset.h>

@class NSMutableArray, NSSet;

@interface MCAssetVideo : MCAsset {

	NSMutableArray* mSlides;

}

@property (readonly) NSSet * slides; 
-(void)removeSlide:(id)arg1 ;
-(void)demolish;
-(NSSet *)slides;
-(char)isInUse;
-(void)addSlide:(id)arg1 ;
@end

