/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:41 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusOrigamiProducer.opplugin/OpusOrigamiProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <OpusOrigamiProducer/MCContainer.h>

@class NSMutableDictionary, NSString, MCPlugHaven, NSSet;

@interface MCContainerNavigator : MCContainer {

	NSMutableDictionary* mPlugs;
	NSString* mStartPlugID;
	MCPlugHaven* mStartPlug;

}

@property (readonly) NSSet * plugs; 
@property (readonly) unsigned countOfPlugs; 
@property (nonatomic,copy) NSString * startPlugID; 
@property (readonly) MCPlugHaven * startPlug; 
-(unsigned)countOfPlugs;
-(NSString *)startPlugID;
-(MCPlugHaven *)startPlug;
-(void)setStartPlugID:(NSString *)arg1 ;
-(void)removeAllPlugs;
-(id)initWithImprint:(id)arg1 andMontage:(id)arg2 ;
-(void)demolish;
-(id)setPlugForContainer:(id)arg1 forID:(id)arg2 ;
-(void)removePlugForID:(id)arg1 ;
-(void)changeIDOfPlug:(id)arg1 toID:(id)arg2 ;
-(id)plugForID:(id)arg1 ;
-(NSSet *)plugs;
-(void)removePlug:(id)arg1 ;
-(id)init;
-(id)imprint;
@end

