/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:42 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusOrigamiProducer.opplugin/OpusOrigamiProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDictionary, NSMutableDictionary, NSRecursiveLock, MCPlug, NSString, NSArray;

@interface MCMontage : NSObject {

	NSDictionary* mImprintWhileLoading;
	NSMutableDictionary* mVideoAssetsForFilePaths;
	NSMutableDictionary* mVideoAssetsForObjectIDs;
	NSMutableDictionary* mAudioAssetsForFilePaths;
	NSMutableDictionary* mAudioAssetsForObjectIDs;
	NSMutableDictionary* mContainersForObjectIDs;
	NSRecursiveLock* mLock;
	unsigned char _styleHint;
	MCPlug* mRootPlug;
	NSString* mBasePath;
	NSArray* mLayouts;
	double mFadeInDuration;
	double mFadeOutDuration;
	double mAudioFadeOutDuration;
	unsigned long long mUUIDSeed;

}

@property (nonatomic,readonly) MCPlug * rootPlug; 
@property (assign,nonatomic) double fadeInDuration; 
@property (assign,nonatomic) double fadeOutDuration; 
@property (assign,nonatomic) double audioFadeOutDuration; 
@property (copy) NSString * basePath; 
@property (nonatomic,readonly) unsigned long long uuidSeed; 
@property (retain) NSArray * layouts; 
@property (assign,nonatomic) unsigned char styleHint;                    //@synthesize styleHint=_styleHint - In the implementation block
-(unsigned long long)uuidSeed;
-(void)setStyleHint:(unsigned char)arg1 ;
-(MCPlug *)rootPlug;
-(unsigned char)styleHint;
-(id)audioAssetForFileAtPath:(id)arg1 ;
-(id)assetForObjectID:(id)arg1 ;
-(void)registerContainer:(id)arg1 ;
-(id)audioAssets;
-(void)demolish;
-(id)containerForObjectID:(id)arg1 ;
-(id)createSerializerContainer;
-(id)createEffectContainer;
-(id)createNavigatorContainer;
-(void)forgetAboutContainer:(id)arg1 ;
-(id)videoAssetForFileAtPath:(id)arg1 ;
-(id)createParallelizerContainer;
-(id)videoAssetForObjectID:(id)arg1 ;
-(id)audioAssetForObjectID:(id)arg1 ;
-(id)initFromScratch;
-(void)setLayouts:(NSArray *)arg1 ;
-(id)assets;
-(NSArray *)layouts;
-(void)dealloc;
-(id)init;
-(id)data;
-(void)lock;
-(void)unlock;
-(void)setFadeInDuration:(double)arg1 ;
-(void)setFadeOutDuration:(double)arg1 ;
-(double)fadeInDuration;
-(double)fadeOutDuration;
-(id)videoAssets;
-(id)imprint;
-(void)setBasePath:(NSString *)arg1 ;
-(NSString *)basePath;
-(double)audioFadeOutDuration;
-(void)setAudioFadeOutDuration:(double)arg1 ;
-(id)initWithData:(id)arg1 error:(id*)arg2 ;
@end

