/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:42 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusOrigamiProducer.opplugin/OpusOrigamiProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MPAutomaticLayerSupport
@required
-(void)removeAllLayers;
-(void)moveLayersFromIndices:(id)arg1 toIndex:(int)arg2;
-(void)insertLayers:(id)arg1 atIndex:(int)arg2;
-(void)removeLayersAtIndices:(id)arg1;
-(id)layers;
-(void)addLayers:(id)arg1;
-(void)addLayer:(id)arg1;

@end

