/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:43 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusOrigamiProducer.opplugin/OpusOrigamiProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface MPFrameManager : NSObject {

	NSMutableDictionary* mFrames;
	NSMutableDictionary* mCategories;

}
+(void)loadFrameManagerWithPaths:(id)arg1 ;
+(void)releaseSharedManager;
+(id)sharedManager;
-(id)allFrameIDs;
-(id)attributesForFrameID:(id)arg1 andPresetID:(id)arg2 ;
-(id)versionOfFrameID:(id)arg1 ;
-(id)categoryIDsForFrameID:(id)arg1 ;
-(id)framesForCategoryID:(id)arg1 ;
-(id)randomFrameFromList:(id)arg1 abidingWithConstraints:(id)arg2 ;
-(id)localizedCategoryNameFromCategoryID:(id)arg1 ;
-(id)localizedFrameNameForFrameID:(id)arg1 ;
-(id)constraintsForFramesMatchingList:(id)arg1 andCriteria:(id)arg2 ;
-(id)allCategoryIDs;
-(id)descriptionForFrameID:(id)arg1 ;
-(void)dealloc;
-(id)initWithPaths:(id)arg1 ;
@end

