/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:42 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusOrigamiProducer.opplugin/OpusOrigamiProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <OpusOrigamiProducer/OpusOrigamiProducer-Structs.h>
#import <libobjc.A.dylib/NSCoding.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <OpusOrigamiProducer/MPFilterSupport.h>
#import <OpusOrigamiProducer/MPAnimationSupport.h>

@protocol MPEffectSupport;
@class MPFrame, NSMutableDictionary, NSString, MPLayerGroup, NSMutableArray, MCSlide, NSObject;

@interface MPSlide : NSObject <NSCoding, NSCopying, MPFilterSupport, MPAnimationSupport> {

	MPFrame* _frame;
	NSMutableDictionary* _attributes;
	NSString* _path;
	MPLayerGroup* _layerGroup;
	NSMutableArray* _filters;
	NSMutableDictionary* _animationPaths;
	MCSlide* _slide;
	NSObject*<MPEffectSupport> _parent;
	double _startTime;
	double _duration;
	double _audioFadeInDuration;
	double _audioFadeOutDuration;
	double _audioDuckInDuration;
	double _audioDuckOutDuration;
	double _audioDuckLevel;
	float _scale;
	float _rotation;
	CGPoint _center;
	float _audioVolume;
	NSString* _sizingMode;
	unsigned _mediaType;
	char _isSecondary;
	char _mirrorToDuplicatePaths;
	double _cachedShowTime;
	double _cachedShowDuration;
	CGSize _cachedSize;

}

@property (nonatomic,retain) MPFrame * frame; 
@property (nonatomic,copy) NSString * path; 
@property (nonatomic,copy) NSString * absolutePath; 
@property (nonatomic,retain) MPLayerGroup * layerGroup; 
@property (assign,nonatomic) double duration; 
@property (assign,nonatomic) double startTime; 
@property (assign,nonatomic) float audioVolume; 
@property (assign,nonatomic) double audioFadeInDuration; 
@property (assign,nonatomic) double audioFadeOutDuration; 
@property (assign,nonatomic) double audioDuckInDuration; 
@property (assign,nonatomic) double audioDuckOutDuration; 
@property (assign,nonatomic) float audioDuckLevel; 
@property (nonatomic,copy) NSString * sizingMode; 
@property (assign,nonatomic) CGPoint center; 
@property (assign,nonatomic) float scale; 
@property (assign,nonatomic) float rotation; 
+(id)slideWithPath:(id)arg1 ;
+(id)slide;
-(void)setAbsolutePath:(NSString *)arg1 ;
-(void)setIsSecondary:(char)arg1 ;
-(void)copyFrame:(id)arg1 ;
-(void)setSlide:(id)arg1 ;
-(id)nearestLayer;
-(id)parentEffect;
-(void)copyLayerGroup:(id)arg1 ;
-(int)liveIndex;
-(void)setSizingMode:(NSString *)arg1 ;
-(void)copyFilters:(id)arg1 ;
-(double)showTime;
-(void)setLayerGroup:(MPLayerGroup *)arg1 ;
-(double)showDisplayTime;
-(NSString *)sizingMode;
-(void)copyVars:(id)arg1 ;
-(double)showDuration;
-(double)showDisplayStartTime;
-(id)parentSubtitleEffect;
-(void)duplicateAnimationPaths;
-(void)setUserInfoAttribute:(id)arg1 forKey:(id)arg2 ;
-(double)audioFadeInDuration;
-(double)audioDuckInDuration;
-(double)audioDuckOutDuration;
-(void)resetCachedTimes;
-(id)userInfoAttributeForKey:(id)arg1 ;
-(void)insertFilters:(id)arg1 atIndex:(int)arg2 ;
-(void)removeAllFilters;
-(void)removeFiltersAtIndices:(id)arg1 ;
-(void)moveFiltersFromIndices:(id)arg1 toIndex:(int)arg2 ;
-(char)determineShowTime:(double*)arg1 showDuration:(double*)arg2 ;
-(void)setAudioFadeInDuration:(double)arg1 ;
-(void)setAudioDuckInDuration:(double)arg1 ;
-(void)setAudioDuckOutDuration:(double)arg1 ;
-(void)setAudioDuckLevel:(float)arg1 ;
-(char)isPanoramaInDocument:(id)arg1 ;
-(float)audioDuckLevel;
-(void)copyAnimationPaths:(id)arg1 ;
-(void)removeAnimationPathForKey:(id)arg1 ;
-(void)setAnimationPath:(id)arg1 forKey:(id)arg2 ;
-(id)animationPathForKey:(id)arg1 ;
-(id)parentDocument;
-(id)animationPaths;
-(id)fullDebugLog;
-(int)countOfFilter;
-(void)replaceObjectInFilterAtIndex:(int)arg1 withObject:(id)arg2 ;
-(id)scriptingFrame;
-(id)objectInFilterAtIndex:(int)arg1 ;
-(id)scriptingAnimations;
-(char)hasAnimationPathForKey:(id)arg1 ;
-(id)keyframedAnimationPathForKey:(id)arg1 ;
-(void)removeObjectFromFilterAtIndex:(int)arg1 ;
-(char)canZoom;
-(void)setScriptingFrame:(id)arg1 ;
-(void)setMirrorToDuplicatePaths:(char)arg1 ;
-(id)initWithLayerGroup:(id)arg1 ;
-(MPLayerGroup *)layerGroup;
-(void)setKeyframedAnimationPath:(id)arg1 forKey:(id)arg2 ;
-(void)insertObject:(id)arg1 inFilterAtIndex:(int)arg2 ;
-(void)setScriptingAnimations:(id)arg1 ;
-(char)needsStyleUpdateOnSlideChange;
-(char)needsTimingUpdateOnSlideChange;
-(float)originalAspectRatio;
-(double)maxDuration;
-(void)dump;
-(float)aspectRatio;
-(void)setMediaType:(unsigned)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)setFrame:(MPFrame *)arg1 ;
-(MPFrame *)frame;
-(id)description;
-(double)duration;
-(void)setDuration:(double)arg1 ;
-(void)setStartTime:(double)arg1 ;
-(void)setScale:(float)arg1 ;
-(id)action;
-(NSString *)path;
-(float)scale;
-(CGPoint)center;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setCenter:(CGPoint)arg1 ;
-(id)filters;
-(int)index;
-(void)setPath:(NSString *)arg1 ;
-(void)setRotation:(float)arg1 ;
-(float)rotation;
-(id)initWithPath:(id)arg1 ;
-(double)startTime;
-(void)cleanup;
-(NSString *)absolutePath;
-(void)addFilters:(id)arg1 ;
-(char)hasMovie;
-(id)parent;
-(void)setParent:(id)arg1 ;
-(char)isSecondary;
-(void)addFilter:(id)arg1 ;
-(id)slide;
-(double)audioFadeOutDuration;
-(void)setAudioVolume:(float)arg1 ;
-(void)setAudioFadeOutDuration:(double)arg1 ;
-(float)audioVolume;
@end

