/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:42 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusOrigamiProducer.opplugin/OpusOrigamiProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MPTimingSupport
@required
-(char)startsPaused;
-(void)setTimeIn:(double)arg1;
-(void)setStartsPaused:(char)arg1;
-(double)timeIn;
-(double)phaseInDuration;
-(void)setPhaseInDuration:(double)arg1;
-(double)phaseOutDuration;
-(void)setPhaseOutDuration:(double)arg1;
-(void)setIsTriggered:(char)arg1;
-(char)isTriggered;
-(void)setNumberOfLoops:(double)arg1;
-(double)numberOfLoops;
-(double)duration;
-(void)setDuration:(double)arg1;

@end

