/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:43 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusOrigamiProducer.opplugin/OpusOrigamiProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface MPTransitionManager : NSObject {

	NSMutableDictionary* mTransitions;
	NSMutableDictionary* mTransitionCategories;
	NSMutableDictionary* mTransitionPresets;

}
+(void)loadTransitionManagerWithPaths:(id)arg1 ;
+(void)releaseSharedManager;
+(id)sharedManager;
-(int)transitionNeedsRandomSeedInformation:(id)arg1 ;
-(double)defaultDurationForTransitionID:(id)arg1 ;
-(id)versionOfTransitionID:(id)arg1 ;
-(float)beatStrengthForTransitionID:(id)arg1 ;
-(id)categoryIDsForTransitionID:(id)arg1 ;
-(id)transitionsForCategoryID:(id)arg1 ;
-(id)settingsUIControlDescriptionsForTransition:(id)arg1 ;
-(id)descriptionForTransitionID:(id)arg1 ;
-(id)attributesForTransitionID:(id)arg1 andPresetID:(id)arg2 ;
-(id)transitionPresetsMatchingCriteria:(id)arg1 ;
-(id)localizedTransitionNameForTransitionID:(id)arg1 ;
-(id)localizedNameForTransitionID:(id)arg1 withLanguage:(id)arg2 ;
-(id)localizedTransitionNameForTransitionID:(id)arg1 andPresetID:(id)arg2 ;
-(id)localizedCategoryNameFromCategoryID:(id)arg1 ;
-(id)constraintsForTransitionPresetsMatchingList:(id)arg1 andCriteria:(id)arg2 ;
-(id)randomTransitionPresetFromList:(id)arg1 abidingWithConstraints:(id)arg2 ;
-(id)allTransitionIDs;
-(double)bestBeatTimeForTransitionID:(id)arg1 ;
-(id)localizedSettingsUITitleForTitleKey:(id)arg1 inTransition:(id)arg2 ;
-(id)controlForAttribute:(id)arg1 forTransitionID:(id)arg2 ;
-(id)presetsForTransitionID:(id)arg1 ;
-(id)allCategoryIDs;
-(void)dealloc;
-(id)initWithPaths:(id)arg1 ;
@end

