/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:43 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusOrigamiProducer.opplugin/OpusOrigamiProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <OpusOrigamiProducer/OpusOrigamiProducer-Structs.h>
@interface MPVector : NSObject {

	float _vector[4];
	int _length;

}
+(id)vectorFromCGColor:(CGColorRef)arg1 ;
+(id)vectorWithValues:(id)arg1 ;
+(id)vectorFromMCVector:(SCD_Struct_MC13)arg1 ;
+(id)vectorFromString:(id)arg1 ;
-(id)CIColorString;
-(void)setVector:(SCD_Struct_MC13)arg1 ;
-(float)valueAtIndex:(int)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(CGColorRef)CGColor;
-(void)encodeWithCoder:(id)arg1 ;
-(int)count;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)string;
-(void)setValues:(id)arg1 ;
-(id)values;
-(char)isEqualTo:(id)arg1 ;
-(SCD_Struct_MC13)vector;
@end

