/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:44 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusOrigamiProducer.opplugin/OpusOrigamiProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MRMarimbaHitBlobSupport
@required
-(void)endGesture:(id)arg1;
-(char)endLiveUpdateForHitBlob:(id)arg1;
-(char)beginLiveUpdateForHitBlob:(id)arg1;
-(CGPoint*)convertPoint:(CGPoint)arg1 toHitBlob:(id)arg2;
-(id)blobHitAtPoint:(CGPoint)arg1 fromObjectsForObjectIDs:(id)arg2 localPoint:(CGPoint*)arg3;
-(void)cancelGesture:(id)arg1;
-(char)getOnScreenVertices:(CGPoint)arg1 forHitBlob:(id)arg2;
-(void)doGesture:(id)arg1;
-(void)beginGesture:(id)arg1;

@end

