/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:43 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusOrigamiProducer.opplugin/OpusOrigamiProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <OpusOrigamiProducer/OpusOrigamiProducer-Structs.h>
#import <OpusOrigamiProducer/MRLoadable.h>
#import <OpusOrigamiProducer/MRRenderable.h>
#import <OpusOrigamiProducer/MRAssetPlayerDelegate.h>

@class NSString, NSDictionary, NSInvocationOperation, NSLock, MRFrame, MRImage, MRLayerEffect, MRAssetPlayer, MRLayer, MRAudioDucker, MCSlide, MCAnimationPathKeyframed;

@interface MRSlideProvider : NSObject <MRLoadable, MRRenderable, MRAssetPlayerDelegate> {

	CGSize mDefaultSize;
	float mStillTime;
	NSString* mImageSizeScript;
	NSDictionary* mEffectAttributes;
	NSString* mShowTimeScript;
	NSInvocationOperation* mPreloadOperation;
	NSLock* mPreloadOperationLock;
	MRFrame* mFrame;
	MRImage* mOriginalImage;
	MRImage* mOutputImage;
	CGSize mRequestedSize;
	MRLayerEffect* mEffectLayer;
	int mKenBurnsType;
	MRAssetPlayer* mSlidePlayer;
	MRLayer* mSlideLayer;
	unsigned mSlideIndex;
	CGSize mImageSize;
	CGSize mLastImageSize;
	double mLastTime;
	CGSize mLastDaSize;
	CGSize mSizeFactor;
	unsigned mFlags;
	double _centerAnimationPathTriggerTime;
	double _scaleAnimationPathTriggerTime;
	double _rotationAnimationPathTriggerTime;
	double _timeToPreloadFor;
	MRAudioDucker* _audioDucker;
	MCSlide* _slide;
	int mDefaultKenBurnsType;
	float mOriginalImageAspectRatio;
	NSString* _assetPath;
	float _scale;
	float _rotation;
	MCAnimationPathKeyframed* _centerAnimationPath;
	MCAnimationPathKeyframed* _scaleAnimationPath;
	MCAnimationPathKeyframed* _rotationAnimationPath;
	NSString* _filterID;
	id _playerHint;
	double _showTime;
	double _showDuration;
	double _slideStartTime;
	double _slideDuration;
	CGPoint _center;

}

@property (assign,nonatomic) CGSize defaultSize; 
@property (assign,nonatomic) char wantsMonochromatic; 
@property (assign,nonatomic) char wantsMipmap; 
@property (assign,nonatomic) char isStill; 
@property (assign,nonatomic) float stillTime; 
@property (nonatomic,copy) NSString * imageSizeScript; 
@property (nonatomic,retain) NSDictionary * effectAttributes; 
@property (nonatomic,copy) NSString * showTimeScript; 
@property (assign,nonatomic) char slideIsReadonly; 
@property (assign,nonatomic) char isMuted; 
@property (readonly) char hasFilters; 
@property (assign,nonatomic) double showTime;                                               //@synthesize showTime=_showTime - In the implementation block
@property (assign,nonatomic) double showDuration;                                           //@synthesize showDuration=_showDuration - In the implementation block
@property (readonly) char canPlay; 
@property (assign,nonatomic) char isPlaying; 
@property (assign,nonatomic) double time; 
@property (assign,nonatomic) CGSize sizeFactor; 
@property (assign) int defaultKenBurnsType; 
@property (nonatomic,retain) MCSlide * slide;                                               //@synthesize slide=_slide - In the implementation block
@property (nonatomic,copy) NSString * assetPath;                                            //@synthesize assetPath=_assetPath - In the implementation block
@property (assign,nonatomic) CGPoint center;                                                //@synthesize center=_center - In the implementation block
@property (assign,nonatomic) float scale;                                                   //@synthesize scale=_scale - In the implementation block
@property (assign,nonatomic) float rotation;                                                //@synthesize rotation=_rotation - In the implementation block
@property (nonatomic,retain) MCAnimationPathKeyframed * centerAnimationPath;                //@synthesize centerAnimationPath=_centerAnimationPath - In the implementation block
@property (nonatomic,retain) MCAnimationPathKeyframed * scaleAnimationPath;                 //@synthesize scaleAnimationPath=_scaleAnimationPath - In the implementation block
@property (nonatomic,retain) MCAnimationPathKeyframed * rotationAnimationPath;              //@synthesize rotationAnimationPath=_rotationAnimationPath - In the implementation block
@property (nonatomic,copy) NSString * filterID;                                             //@synthesize filterID=_filterID - In the implementation block
@property (assign,nonatomic) char needsToUpdateLayout; 
@property (readonly) MRFrame * frame; 
@property (readonly) CGSize requestedSize; 
@property (readonly) float imageAspectRatio; 
@property (readonly) double slideStartTime;                                                 //@synthesize slideStartTime=_slideStartTime - In the implementation block
@property (readonly) double slideDuration;                                                  //@synthesize slideDuration=_slideDuration - In the implementation block
@property (readonly) char isLoaded; 
@property (assign) id playerHint;                                                           //@synthesize playerHint=_playerHint - In the implementation block
@property (nonatomic,readonly) char isNative3D; 
@property (nonatomic,readonly) char isOpaque; 
@property (nonatomic,readonly) char isAlphaFriendly; 
@property (nonatomic,readonly) char isInfinite; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSString *)assetPath;
-(void)setAssetPath:(NSString *)arg1 ;
-(char)wantsMipmap;
-(double)slideDuration;
-(void)setSlide:(MCSlide *)arg1 ;
-(void)setDefaultSize:(CGSize)arg1 ;
-(NSString *)imageSizeScript;
-(char)isStill;
-(void)setStillTime:(float)arg1 ;
-(void)setIsPlaying:(char)arg1 ;
-(id)playerHint;
-(double)showTime;
-(char)slideIsReadonly;
-(CGSize)sizeFactor;
-(char)hasFilters;
-(double)slideStartTime;
-(char)beginLiveUpdate;
-(void)setWantsMipmap:(char)arg1 ;
-(char)endLiveUpdate;
-(double)showDuration;
-(void)printFlags;
-(id)retainedByUserRenderedImageAtTime:(double)arg1 inContext:(id)arg2 withArguments:(id)arg3 ;
-(float)stillTime;
-(NSDictionary *)effectAttributes;
-(char)isLoadedForTime:(double)arg1 ;
-(void)setPlayerHint:(id)arg1 ;
-(void)setNeedsToUpdateLayout:(char)arg1 ;
-(char)updateStuffWithAssetManager:(id)arg1 ;
-(void)setDefaultKenBurnsType:(int)arg1 ;
-(id)currentSlideInfo;
-(id)initWithEffectLayer:(id)arg1 ;
-(void)setSlideIsReadonly:(char)arg1 ;
-(void)setImageSizeScript:(NSString *)arg1 ;
-(NSString *)showTimeScript;
-(void)setShowTimeScript:(NSString *)arg1 ;
-(void)updateShowTimeAndDurationWithPlugTiming:(id)arg1 andAttributes:(id)arg2 ;
-(void)setIsStill:(char)arg1 ;
-(void)setShowTime:(double)arg1 ;
-(void)applyKenBurnsAtTime:(double)arg1 withTargetSize:(CGSize)arg2 kenBurnsType:(int)arg3 translation:(CGPoint*)arg4 scale:(float*)arg5 rotation:(float*)arg6 ;
-(char)wantsMonochromatic;
-(void)imageIsAvailableFromAssetPlayer:(id)arg1 ;
-(void)_unloadIfNotUpdatingLive;
-(CGSize)framedImageSizeAtIndex:(unsigned long)arg1 aspectRatio:(float)arg2 ;
-(void)setCenterAnimationPath:(MCAnimationPathKeyframed *)arg1 ;
-(void)setScaleAnimationPath:(MCAnimationPathKeyframed *)arg1 ;
-(void)setRotationAnimationPath:(MCAnimationPathKeyframed *)arg1 ;
-(void)setWantsMonochromatic:(char)arg1 ;
-(CGSize)unframedImageSizeForAspectRatio:(float)arg1 frameID:(id)arg2 andFrameAttributes:(id)arg3 atIndex:(unsigned long)arg4 framedImageSize:(CGSize*)arg5 ;
-(void)_computeImageSizeInContext:(id)arg1 withArguments:(id)arg2 ;
-(int)defaultKenBurnsType;
-(void)setEffectAttributes:(NSDictionary *)arg1 ;
-(char)isAlphaFriendly;
-(id)patchworkAtTime:(double)arg1 inContext:(id)arg2 withArguments:(id)arg3 ;
-(char)prerenderForTime:(double)arg1 inContext:(id)arg2 withArguments:(id)arg3 ;
-(void)loadForTime:(double)arg1 inContext:(id)arg2 withArguments:(id)arg3 now:(char)arg4 ;
-(void)renderAtTime:(double)arg1 inContext:(id)arg2 withArguments:(id)arg3 ;
-(void)loadWithArguments:(id)arg1 ;
-(char)needsToUpdateLayout;
-(MCAnimationPathKeyframed *)scaleAnimationPath;
-(MCAnimationPathKeyframed *)centerAnimationPath;
-(MCAnimationPathKeyframed *)rotationAnimationPath;
-(void)setSizeFactor:(CGSize)arg1 ;
-(char)isNative3D;
-(void)cancelLoading;
-(char)isPlaying;
-(void)dealloc;
-(CGSize)defaultSize;
-(MRFrame *)frame;
-(void)setScale:(float)arg1 ;
-(float)scale;
-(CGPoint)center;
-(void)setCenter:(CGPoint)arg1 ;
-(char)isOpaque;
-(void)setTime:(double)arg1 ;
-(double)time;
-(void)setShowDuration:(double)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)setRotation:(float)arg1 ;
-(float)rotation;
-(char)isLoaded;
-(void)cleanup;
-(void)setFilterID:(NSString *)arg1 ;
-(NSString *)filterID;
-(CGSize)requestedSize;
-(void)unload;
-(MCSlide *)slide;
-(char)isMuted;
-(void)setIsMuted:(char)arg1 ;
-(char)isInfinite;
-(float)imageAspectRatio;
-(char)canPlay;
@end

