/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:42 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusOrigamiProducer.opplugin/OpusOrigamiProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <OpusOrigamiProducer/MRTransition.h>

@class MROrigamiAnimationPath;

@interface MRTransitionOrigamiFlip : MRTransition {

	MROrigamiAnimationPath* mBigSwing;
	MROrigamiAnimationPath* mSideSwing;

}
-(char)supportsDirectionOverride;
-(char)controlsLayersTime;
-(id)initWithTransitionID:(id)arg1 ;
-(void)_setupSwingTimings;
-(void)_cleanupSwingTimings;
-(char)prerenderForTime:(double)arg1 inContext:(id)arg2 withArguments:(id)arg3 ;
-(void)renderAtTime:(double)arg1 inContext:(id)arg2 withArguments:(id)arg3 ;
-(void)setAttributes:(id)arg1 ;
-(void)cleanup;
@end

