/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:43 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusOrigamiProducer.opplugin/OpusOrigamiProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MZEffectTiming
@property (nonatomic,readonly) double phaseInDuration; 
@property (nonatomic,readonly) double mainDuration; 
@property (nonatomic,readonly) double phaseOutDuration; 
@optional
-(NSRange*)multiImageSlideRange;
-(unsigned)effectAuthoredSlideCount;
-(id)effectAuthoredAttributes;
-(void)appendSlideInformation:(id)arg1 andTextInformation:(id)arg2;
-(void)setMultiImageSlideRange:(NSRange)arg1;

@required
-(double)mainDuration;
-(double)lowestDisplayTime;
-(void)setPhaseInDuration:(double)arg1 mainDuration:(double)arg2 phaseOutDuration:(double)arg3;
-(double)showTimeForSlideAtIndex:(unsigned)arg1;
-(double)showDurationForSlideAtIndex:(unsigned)arg1;
-(double)displayTimeForSlideAtIndex:(unsigned)arg1;
-(double)phaseInDuration;
-(double)phaseOutDuration;
-(double)displayTimeForTextAtIndex:(unsigned)arg1;

@end

