/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:38:09 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/PassKit.framework/PassKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MapKit/_MKPlaceViewController.h>
#import <libobjc.A.dylib/_MKPlaceViewControllerDelegate.h>

@class NSString;

@interface PKMerchantMapViewController : _MKPlaceViewController <_MKPlaceViewControllerDelegate>

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)activityViewControllerForPlaceViewController:(id)arg1 ;
-(void)placeViewControllerDidSelectShareLocation;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLoad;
@end

