/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:38:09 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/PassKit.framework/PassKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class UITraitCollection;


@protocol UITraitEnvironment <NSObject>
@property (nonatomic,readonly) UITraitCollection * traitCollection; 
@required
-(UITraitCollection *)traitCollection;
-(void)traitCollectionDidChange:(id)arg1;

@end

