/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:14:50 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/AccountNotification.framework/and
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSManagedObjectContext, NSPersistentStoreCoordinator;

@interface ANNotificationStore : NSObject {

	NSManagedObjectContext* _managedObjectContext;
	NSPersistentStoreCoordinator* _storeCoordinator;

}
+(id)sharedStore;
-(void)_createManagedObjectContext;
-(id)_notificationsMatchingPredicate:(id)arg1 ;
-(id)_notificationsMatchingPredicate:(id)arg1 limit:(unsigned)arg2 ;
-(char)_unsafe_commitChangesInManagedObjectContext;
-(id)_copyPersistentStoreFilePath;
-(id)pendingNotificationsForAccountsWithTypeID:(id)arg1 ;
-(id)notificationWithIdentifier:(id)arg1 ;
-(id)pendingNotificationsWithEventID:(id)arg1 ;
-(id)typeIdentifiersOfAccountsWithPendingNotifications;
-(char)saveNotification:(id)arg1 ;
-(char)limitPendingNotificationsForAccountTypeID:(id)arg1 toMaximumCount:(unsigned)arg2 ;
-(char)removeAllNotificationsForAccountTypeID:(id)arg1 ;
-(id)_managedObjectModel;
-(id)init;
-(char)removeNotificationWithIdentifier:(id)arg1 ;
@end

