/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:00 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/ApplePushService.framework/apsd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol APSAppLaunchStatsDelegate <NSObject>
@required
-(void)resourceUpdate:(unsigned)arg1 withStatus:(unsigned)arg2;
-(void)pendingWorkCanProcess:(id)arg1;

@end

