/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:00 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/ApplePushService.framework/apsd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class APSIDSProxyManager;


@protocol APSCourierDelegate <NSObject>
@property (nonatomic,retain,readonly) APSIDSProxyManager * proxyManager; 
@required
-(void)courierHasNoConnections:(id)arg1;
-(APSIDSProxyManager *)proxyManager;
-(void)courierConnectionStatusDidChange:(id)arg1;
-(void)shouldUseInternetDidChange:(id)arg1;

@end

