/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:20 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/MusicCarDisplayUI.framework/MusicCarDisplayUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UIImageView, UIImage;

@interface MCDTableViewCell : UITableViewCell {

	UIImageView* _artworkImageView;
	float _originalLeadingInset;

}

@property (nonatomic,retain) UIImage * artworkImage; 
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(void)setArtworkImage:(UIImage *)arg1 ;
-(UIImage *)artworkImage;
@end

