/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:28 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SafariShared.framework/XPCServices/com.apple.Safari.WebFeedParser.xpc/com.apple.Safari.WebFeedParser
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol WBSFeedParserDelegate <NSObject>
@required
-(void)feedParser:(id)arg1 failedParsingFeedWithError:(id)arg2;
-(void)feedParser:(id)arg1 parsedFeedWithMetadata:(id)arg2 entries:(id)arg3;

@end

