/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:24:01 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/HealthKit.framework/HealthKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface _HKBehavior : NSObject
+(id)currentDiskUsage;
+(id)currentDeviceManufacturer;
+(id)currentDeviceClass;
+(char)isCoachingEventLoggingEnabled;
+(char)isAppleInternalInstall;
+(id)currentOSBuild;
+(char)isDeviceSupported;
+(char)isNano;
+(char)isCompanionCapable;
+(id)currentDeviceProductType;
+(id)currentInternalDeviceModel;
+(id)currentOSVersion;
+(unsigned long long)totalDiskCapacity;
+(unsigned long long)currentDiskSpaceAvailable;
+(id)currentDeviceName;
+(id)currentDeviceDisplayName;
@end

