/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:24:00 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/HealthKit.framework/HealthKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface _HKCFGNodeCache : NSObject {

	NSMutableDictionary* _cache;

}
-(id)nodesForPosition:(unsigned)arg1 nonTerminal:(id)arg2 withLengthAllowance:(unsigned)arg3 ;
-(void)cacheNodes:(id)arg1 forPosition:(unsigned)arg2 nonTerminal:(id)arg3 lengthAllowance:(unsigned)arg4 ;
-(id)init;
@end

