/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:24:00 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/HealthKit.framework/HealthKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <HealthKit/_HKCFGNode.h>

@interface _HKCFGEmptyStringNode : _HKCFGNode {

	/*^block*/id _evaluator;

}
+(id)nodeWithEvaluator:(/*^block*/id)arg1 ;
-(id)evaluate;
@end

