/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:33:48 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/MetalKit.framework/MetalKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MDLMeshBufferZone <NSObject>
@property (nonatomic,readonly) unsigned capacity; 
@property (nonatomic,readonly) id<MDLMeshBufferAllocator> allocator; 
@required
-(id<MDLMeshBufferAllocator>)allocator;
-(unsigned)capacity;

@end

