/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:52 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PLCommentsViewControllerDelegate <NSObject>
@optional
-(void)commentsControllerInactiveAreaWasTapped:(id)arg1;
-(void)commentsControllerWillEnterEditMode:(id)arg1;
-(void)commentsControllerDidExitEditMode:(id)arg1;
-(void)commentsControllerDidDisplayUnreadComment:(id)arg1;
-(void)commentsControllerWillBeginScrolling:(id)arg1;
-(void)commentsControllerDidScroll:(id)arg1;
-(char)commentsControllerShouldUseTextEntryCell:(id)arg1;

@end

