/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:53 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CoreTime.framework/TimeSources/LinkSource.bundle/LinkSource
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <LinkSource/LinkSource-Structs.h>
#import <LinkSource/TMLSLinkDelegate.h>

@protocol TMMonotonicClock;
@class NSDictionary, TMLSLink, NSString;

@interface TMLSLinkSource : NSObject <TMLSLinkDelegate> {

	NSDictionary* _lastCompanionTimeUpdate;
	char _coalescingUpdates;
	char _gizmo;
	id<TMMonotonicClock> _clock;
	id _daemonCore;
	TMLSLink* _link;
	NSString* _companionTimeZone;
	SCD_Struct_TM0 _lastRTCSample;

}

@property (nonatomic,retain) id<TMMonotonicClock> clock;                                       //@synthesize clock=_clock - In the implementation block
@property (assign,nonatomic,__weak) id daemonCore;                                             //@synthesize daemonCore=_daemonCore - In the implementation block
@property (nonatomic,retain) TMLSLink * link;                                                  //@synthesize link=_link - In the implementation block
@property (assign,nonatomic) SCD_Struct_TM0 lastRTCSample;                                     //@synthesize lastRTCSample=_lastRTCSample - In the implementation block
@property (nonatomic,copy) NSString * companionTimeZone;                                       //@synthesize companionTimeZone=_companionTimeZone - In the implementation block
@property (assign,getter=isLastRTCSampleValid,nonatomic) char lastRTCSampleValid; 
@property (assign,getter=isGizmo,nonatomic) char gizmo;                                        //@synthesize gizmo=_gizmo - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)systemTimeZoneChanged;
-(void)publishCommand:(id)arg1 ;
-(void)setDaemonCore:(id)arg1 ;
-(id)timeAtRtc:(double)arg1 ;
-(id)initWithClock:(id)arg1 daemonCore:(id)arg2 ;
-(NSString *)companionTimeZone;
-(void)syncAutomaticTimeEnabled;
-(void)link:(id)arg1 didReceiveDrift:(double)arg2 ;
-(SCD_Struct_TM0)lastRTCSample;
-(void)linkDidReceiveReset:(id)arg1 ;
-(void)setCompanionTimeZone:(NSString *)arg1 ;
-(void)setLastRTCSampleValid:(char)arg1 ;
-(char)isLastRTCSampleValid;
-(void)syncTimeZone;
-(void)systemTimeChanged:(id)arg1 ;
-(void)link:(id)arg1 didReceiveTime:(double)arg2 remoteRTC:(double)arg3 uncertainty:(double)arg4 source:(id)arg5 ;
-(void)link:(id)arg1 didReceiveTimeZone:(id)arg2 forSource:(id)arg3 ;
-(void)link:(id)arg1 didReceiveAutomaticTimeEnabled:(char)arg2 ;
-(void)link:(id)arg1 didSyncLocalRTC:(double)arg2 remoteRTC:(double)arg3 uncertainty:(double)arg4 ;
-(id)initWithClock:(id)arg1 ;
-(double)rtcWhenBeyondUncertainty:(double)arg1 ;
-(void)setLastRTCSample:(SCD_Struct_TM0)arg1 ;
-(id)daemonCore;
-(id<TMMonotonicClock>)clock;
-(void)setClock:(id<TMMonotonicClock>)arg1 ;
-(void)setGizmo:(char)arg1 ;
-(char)isGizmo;
-(void)dealloc;
-(id)init;
-(id)dictionary;
-(void)significantTimeChange;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(TMLSLink *)link;
-(void)setLink:(TMLSLink *)arg1 ;
@end

