/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:16:37 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDictionary;

@interface HDSQLiteDatabaseSchema : NSObject {

	NSDictionary* _tables;

}

@property (nonatomic,retain) NSDictionary * tables;              //@synthesize tables=_tables - In the implementation block
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(void)setTables:(NSDictionary *)arg1 ;
-(NSDictionary *)tables;
@end

