/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:16:37 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <HealthDaemon/HDKeyValueSyncEntity.h>

@interface HDUserCharacteristicSyncEntity : HDKeyValueSyncEntity
+(int)category;
+(int)syncEntityType;
+(id)syncEntityDependencies;
+(void)didReceiveKeysAndValuesWithHealthDaemon:(id)arg1 ;
+(int)nanoSyncObjectType;
@end

