/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:24 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/MusicStoreUI.framework/MusicStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iTunesStoreUI/SUMediaItemCellContext.h>

@interface MSTrackListCellContext : SUMediaItemCellContext {

	char _shouldHideContentRating;
	char _showSubtitle;

}

@property (assign,nonatomic) char showSubtitle;                         //@synthesize showSubtitle=_showSubtitle - In the implementation block
@property (assign,nonatomic) char shouldHideContentRating;              //@synthesize shouldHideContentRating=_shouldHideContentRating - In the implementation block
-(char)showSubtitle;
-(char)shouldHideContentRating;
-(void)setShouldHideContentRating:(char)arg1 ;
-(void)setShowSubtitle:(char)arg1 ;
@end

