/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 4:44:02 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol CNContactGroupPickerDelegate <NSObject>
@required
-(id)alreadyPickedGroups;
-(void)contactGroupPickerDidFinish:(id)arg1 withGroup:(id)arg2;
-(void)contactGroupPickerDidCancel:(id)arg1;

@end

