/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 4:44:03 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface CNUIDataCollectorLogger : NSObject
-(void)addValue:(int)arg1 forScalarKey:(id)arg2 ;
-(void)setValue:(int)arg1 forScalarKey:(id)arg2 ;
-(void)setValue:(double)arg1 forDistributionKey:(id)arg2 ;
@end

