/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:33 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/NotesShared.framework/NotesShared
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol NSTextStorageDelegate <NSObject>
@optional
-(void)textStorage:(id)arg1 willProcessEditing:(unsigned)arg2 range:(NSRange)arg3 changeInLength:(int)arg4;
-(void)textStorage:(id)arg1 didProcessEditing:(unsigned)arg2 range:(NSRange)arg3 changeInLength:(int)arg4;

@end

