/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:33 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/NotesShared.framework/NotesShared
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol TTTextStorageStyler <NSObject>
@required
-(void)styleText:(id)arg1 inRange:(NSRange)arg2 fixModelAttributes:(char)arg3;
-(void)resetGuessedFontSizes;
-(id)modelForStyleAttributes:(id)arg1 filterAttributes:(char)arg2;
-(id)styleForModelAttributes:(id)arg1;
-(void)guessFontSizeThresholdsForTTStylesInAttributedString:(id)arg1;

@end

