/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:45:50 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/QuickLook.framework/QuickLook
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <QuickLook/QLWebViewPrintPageHelper.h>

@class UIWebPaginationInfo;

@interface QLWordProcessorPrintPageRenderer : QLWebViewPrintPageHelper {

	UIWebPaginationInfo* _paginationInfo;

}
-(id)pdfDataForPageAtIndex:(int)arg1 printingDone:(char*)arg2 ;
-(id)_paginationInfo;
-(void)dealloc;
-(int)numberOfPages;
@end

