/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:52 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@interface TDLayerMapping : NSManagedObject
-(id)copyDataFromAttributes;
-(void)setAttributesFromCopyData:(id)arg1 ;
@end

