/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:14:46 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/AXRuntime.framework/AXRuntime
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AXRuntime/AXRuntime-Structs.h>
#import <Foundation/NSString.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AXAttributedString : NSString <NSCopying> {

	CFAttributedStringRef _string;

}
+(id)axAttributedStringWithString:(id)arg1 ;
+(id)string;
-(void)setAttribute:(id)arg1 forKey:(id)arg2 withRange:(NSRange)arg3 ;
-(void)removeAttributes:(id)arg1 ;
-(char)isAXAttributedString;
-(id)initWithCFAttributedString:(CFAttributedStringRef)arg1 ;
-(CFAttributedStringRef)cfAttributedString;
-(void)replaceString:(CFStringRef)arg1 ;
-(char)hasAttribute:(id)arg1 ;
-(void)dealloc;
-(id)description;
-(id)substringFromIndex:(unsigned)arg1 ;
-(unsigned)length;
-(void)appendString:(id)arg1 ;
-(void)appendFormat:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)string;
-(id)initWithString:(id)arg1 ;
-(id)attribute:(id)arg1 atIndex:(unsigned)arg2 effectiveRange:(NSRange*)arg3 ;
-(unsigned short)characterAtIndex:(unsigned)arg1 ;
-(id)uppercaseString;
-(id)lowercaseString;
-(id)attributesAtIndex:(int)arg1 effectiveRange:(NSRange*)arg2 ;
-(void)setAttributes:(id)arg1 ;
-(id)attributedSubstringFromRange:(NSRange)arg1 ;
-(void)convertAttachmentsWithBlock:(/*^block*/id)arg1 ;
-(void)appendAXAttributedString:(id)arg1 ;
-(void)enumerateAttributesUsingBlock:(/*^block*/id)arg1 ;
-(void)appendStringOrAXAttributedString:(id)arg1 ;
-(id)attributeValueForKey:(id)arg1 ;
-(id)coalescedFontAttributes;
-(id)axAttributedStringDescription;
-(void)setAttribute:(id)arg1 forKey:(id)arg2 ;
-(id)stringByReplacingOccurrencesOfString:(id)arg1 withString:(id)arg2 options:(unsigned)arg3 range:(NSRange)arg4 ;
-(void)setAttributes:(id)arg1 withRange:(NSRange)arg2 ;
@end

