/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:16:08 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/FitnessUI.framework/FitnessUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableArray;

@interface FIUITransactionCommitCoordinator : NSObject {

	NSMutableArray* _commitHandlers;

}
+(char)addImplicitTransactionCommitHandler:(/*^block*/id)arg1 ;
+(id)_sharedInstance;
-(id)init;
-(char)_addImplicitTransactionCommitHandler:(/*^block*/id)arg1 ;
-(void)_registerCATransactionCommitHandler;
@end

