/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:55 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol _SBIconWallpaperColorClient <NSObject>
@required
-(CGRect*)wallpaperRelativeBounds;
-(char)wantsBlur:(id)arg1;
-(void)setWallpaperColor:(CGColorRef)arg1 phase:(CGSize)arg2;
-(void)setBlurring:(char)arg1;
-(char)isBlurring;

@end

