/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:47 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface SBAppVisibilityPreferences : NSObject {

	char _defaultVisible;
	char _currentlyVisible;

}

@property (readonly) char defaultVisible;              //@synthesize defaultVisible=_defaultVisible - In the implementation block
@property (assign) char currentlyVisible;              //@synthesize currentlyVisible=_currentlyVisible - In the implementation block
-(id)initWithDefaultVisible:(char)arg1 ;
-(char)defaultVisible;
-(char)currentlyVisible;
-(void)setCurrentlyVisible:(char)arg1 ;
-(id)description;
@end

