/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:54 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SBApplicationShortcutMenuContentViewDelegate <NSObject>
@required
-(char)menuContentView:(id)arg1 canActivateShortcutItem:(id)arg2;
-(void)menuContentView:(id)arg1 activateShortcutItem:(id)arg2 index:(int)arg3;

@end

