/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:48 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SBApplicationLifecycleObserver
@required
-(void)applicationsAdded:(id)arg1;
-(void)applicationsModified:(id)arg1;
-(void)applicationsRemoved:(id)arg1;
-(void)applicationsDemoted:(id)arg1;

@end

