/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:56 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIScrollView.h>

@class SBMainAppSwitcherPageView;

@interface SBAppSwitcherItemScrollView : UIScrollView {

	SBMainAppSwitcherPageView* _item;
	int _layoutOrientation;

}

@property (nonatomic,retain) SBMainAppSwitcherPageView * item;              //@synthesize item=_item - In the implementation block
@property (assign,nonatomic) int layoutOrientation;                         //@synthesize layoutOrientation=_layoutOrientation - In the implementation block
-(void)_disableScrolling;
-(void)_enableScrolling;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(SBMainAppSwitcherPageView *)item;
-(int)layoutOrientation;
-(void)setLayoutOrientation:(int)arg1 ;
-(void)setItem:(SBMainAppSwitcherPageView *)arg1 ;
@end

