/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:47 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libobjc.A.dylib/BSDescriptionProviding.h>

@class NSArray, NSString;

@interface SBBreadcrumbState : NSObject <BSDescriptionProviding> {

	NSArray* _breadcrumbIdentifiers;

}

@property (nonatomic,retain,readonly) NSArray * breadcrumbIdentifiers;              //@synthesize breadcrumbIdentifiers=_breadcrumbIdentifiers - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)initialState;
-(id)_initWithIdentifiers:(id)arg1 ;
-(id)_stateWithIdentifiers:(id)arg1 ;
-(id)breadcrumbStateAfterPoppingIdentifier:(id)arg1 ;
-(id)breadcrumbStateAfterPushingIdentifier:(id)arg1 ;
-(id)breadcrumbStateAfterPoppingLastIdentifier;
-(char)containsIdentifer:(id)arg1 ;
-(NSArray *)breadcrumbIdentifiers;
-(NSString *)description;
-(id)descriptionWithMultilinePrefix:(id)arg1 ;
-(id)succinctDescription;
-(id)succinctDescriptionBuilder;
-(id)descriptionBuilderWithMultilinePrefix:(id)arg1 ;
@end

