/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:54 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoardUI/SBAlertItem.h>

@class SBCCButtonModule;

@interface SBCCButtonModuleUnavailableAlertItem : SBAlertItem {

	SBCCButtonModule* _module;

}

@property (nonatomic,retain) SBCCButtonModule * module;              //@synthesize module=_module - In the implementation block
+(char)presentAlertItemForButtonModule:(id)arg1 ;
-(SBCCButtonModule *)module;
-(void)setModule:(SBCCButtonModule *)arg1 ;
-(void)dealloc;
-(char)dismissOnLock;
-(char)allowMenuButtonDismissal;
-(void)configure:(char)arg1 requirePasscodeForActions:(char)arg2 ;
-(char)shouldShowInLockScreen;
@end

