/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:47 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBCenterZoomSettings.h>

@class SBAnimationSettings;

@interface SBCenterAppZoomSettings : SBCenterZoomSettings {

	SBAnimationSettings* _appZoomSettings;
	SBAnimationSettings* _appFadeSettings;
	double _appHeadStart;

}

@property (assign) double appHeadStart;                                //@synthesize appHeadStart=_appHeadStart - In the implementation block
@property (retain) SBAnimationSettings * appZoomSettings;              //@synthesize appZoomSettings=_appZoomSettings - In the implementation block
@property (retain) SBAnimationSettings * appFadeSettings;              //@synthesize appFadeSettings=_appFadeSettings - In the implementation block
+(id)settingsControllerModule;
-(double)appHeadStart;
-(void)setAppHeadStart:(double)arg1 ;
-(SBAnimationSettings *)appZoomSettings;
-(void)setAppZoomSettings:(SBAnimationSettings *)arg1 ;
-(SBAnimationSettings *)appFadeSettings;
-(void)setAppFadeSettings:(SBAnimationSettings *)arg1 ;
@end

