/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:49 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SBDeckSwitcherItemContainerDelegate <NSObject>
@required
-(char)isDisplayItemOfContainerRemovable:(id)arg1;
-(char)shouldShowIconAndLabelOfContainer:(id)arg1;
-(void)killDisplayItemOfContainer:(id)arg1 withVelocity:(float)arg2;
-(char)canSelectDisplayItemOfContainer:(id)arg1 numberOfTaps:(int)arg2;
-(void)selectedDisplayItemOfContainer:(id)arg1;
-(CGRect*)frameForPageViewOfContainer:(id)arg1 fullyPresented:(char)arg2;
-(void)scrollViewKillingProgressUpdated:(float)arg1 ofContainer:(id)arg2;
-(float)minimumVerticalTranslationForKillingOfContainer:(id)arg1;

@end

