/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:50 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SBFolderIconObserver <SBIconObserver>
@required
-(void)folderIcon:(id)arg1 didUpdateGridImage:(id)arg2 forListIndex:(unsigned)arg3 forContainedIconImageUpdate:(id)arg4;

@end

