/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:50 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/_UISettings.h>

@interface SBHomeButtonTimingSettings : _UISettings {

	double _tapDuration;
	double _delay;

}

@property (assign,nonatomic) double tapDuration;              //@synthesize tapDuration=_tapDuration - In the implementation block
@property (assign,nonatomic) double delay;                    //@synthesize delay=_delay - In the implementation block
+(id)createWithDuration:(double)arg1 delay:(double)arg2 ;
+(id)settingsControllerModule;
-(double)tapDuration;
-(void)setTapDuration:(double)arg1 ;
-(id)description;
-(double)delay;
-(void)setDelay:(double)arg1 ;
-(void)setDefaultValues;
-(id)displayName;
@end

