/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:47 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoardUI/SBAlertItem.h>

@class SBApplication, NSString;

@interface SBLaunchAlertItem : SBAlertItem {

	SBApplication* _associatedDisplay;
	int _type;
	NSString* _bundleID;
	char _isDataAlert;
	char _usesCellNetwork;

}
-(id)initWithLaunchAlertType:(int)arg1 dataAlert:(char)arg2 usesCellNetwork:(char)arg3 bundleID:(id)arg4 ;
-(void)setAssociatedWithDisplay:(id)arg1 ;
-(void)_displayDeactivated:(id)arg1 ;
-(id)_customAirplaneModeAlertPrompt;
-(void)dealloc;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(id)alertSheet;
-(char)dismissOnLock;
@end

