/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:52 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBLockOverlayView.h>

@class UIImageView;

@interface SBLockScreenTemperatureWarningView : SBLockOverlayView {

	UIImageView* _warningIconView;

}
-(float)_titleBaseline;
-(float)_subtitleBaseline;
-(float)_iconYPosition;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(id)_titleFont;
-(id)_subtitleFont;
@end

