/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:47 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/_UISettings.h>

@interface SBSpotlightSettings : _UISettings {

	char _enableSpotlightHomeScreenGesture;
	char _enableSpotlightOnMinusPage;

}

@property (assign,nonatomic) char enableSpotlightHomeScreenGesture;              //@synthesize enableSpotlightHomeScreenGesture=_enableSpotlightHomeScreenGesture - In the implementation block
@property (assign,nonatomic) char enableSpotlightOnMinusPage;                    //@synthesize enableSpotlightOnMinusPage=_enableSpotlightOnMinusPage - In the implementation block
+(id)settingsControllerModule;
-(void)setEnableSpotlightHomeScreenGesture:(char)arg1 ;
-(void)setEnableSpotlightOnMinusPage:(char)arg1 ;
-(char)enableSpotlightHomeScreenGesture;
-(char)enableSpotlightOnMinusPage;
-(void)setDefaultValues;
@end

