/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:55 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBStarkWorkspaceTransaction.h>
#import <SpringBoard/SBUIAnimationControllerObserver.h>

@class SBWorkspaceAlert, SBWorkspaceApplication, SBUIAnimationController, NSString;

@interface SBStarkAppToAlertWorkspaceTransaction : SBStarkWorkspaceTransaction <SBUIAnimationControllerObserver> {

	SBWorkspaceAlert* _activatingAlert;
	SBWorkspaceApplication* _topApplication;
	SBUIAnimationController* _animation;
	char _animatedAppDeactivation;
	char _fromStarkLauncher;

}

@property (nonatomic,retain,readonly) SBWorkspaceAlert * alert;              //@synthesize activatingAlert=_activatingAlert - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithTransitionRequest:(id)arg1 ;
-(void)animationController:(id)arg1 willBeginAnimation:(char)arg2 ;
-(void)animationControllerDidFinishAnimation:(id)arg1 ;
-(void)dealloc;
-(NSString *)debugDescription;
-(SBWorkspaceAlert *)alert;
-(void)_didComplete;
-(void)_begin;
@end

