/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:47 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SpringBoard/SBUIMainScreenAnimationController.h>

@protocol SBWorkspaceAlertAnimationProviding;
@interface SBUIAnimationForAlertAnimationProvider : SBUIMainScreenAnimationController {

	id<SBWorkspaceAlertAnimationProviding> _alert;
	char _visible;

}
-(id)initWithTransitionContextProvider:(id)arg1 alert:(id)arg2 visible:(char)arg3 ;
-(void)_startAnimation;
-(void)dealloc;
@end

