/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:35:52 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface SBVoiceControlController : NSObject {

	char _delayedAssistantActivationPending;
	char _headsetDownDelayedActionPerformed;

}
+(char)isVoiceControlVisible;
+(id)sharedInstance;
-(void)configureVoiceControl;
-(void)preheatForMenuButtonWithFireDate:(id)arg1 ;
-(char)handleHomeButtonHeld;
-(void)headsetAvailabilityChanged;
-(void)handleHeadsetButtonDownWithClickCount:(unsigned)arg1 ;
-(char)handleHeadsetButtonUp;
-(char)handleHeadsetButtonUpNotInCall;
-(void)bluetoothDeviceInitiatedVoiceControl:(id)arg1 ;
-(void)bluetoothDeviceEndedVoiceControl:(id)arg1 ;
-(void)_updateNextRecognitionAudioInputPaths:(id)arg1 ;
-(void)_assistantActivationSettingsDidChange:(id)arg1 ;
-(void)_performDelayedHeadsetActionForAssistant;
-(void)_performDelayedHeadsetActionForVoiceControl;
-(void)_prepareDelayedHeadsetAction;
-(void)_cancelDelayedHeadsetAction;
-(id)init;
-(void)_spokenLanguageDidChange:(id)arg1 ;
@end

