/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:20 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/MobileTimer.framework/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol Clock
@property (nonatomic,readonly) int runMode; 
@optional
-(double)updateInterval;
-(double)coarseUpdateInterval;
-(void)updateFlutter;
-(void)updateTimeContinuously:(int)arg1;

@required
-(void)stop;
-(void)start;
-(void)updateTime;
-(int)runMode;

@end

