/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:49 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SBSRemoteAlertClientHandle <NSObject>
@required
-(void)queue_setActive:(char)arg1;
-(id)queue_token;
-(void)queue_noteInvalidWithError:(id)arg1;

@end

