/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:40 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusNewClassicProducer.opplugin/OpusNewClassicProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface OpusNewClassicProducerContext : NSObject {

	unsigned _currentFeederIndex;

}

@property (nonatomic,readonly) unsigned currentFeederIndex;              //@synthesize currentFeederIndex=_currentFeederIndex - In the implementation block
-(unsigned)currentFeederIndex;
-(id)init;
@end

