/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:20:56 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/Foundation.framework/Foundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <Foundation/Foundation-Structs.h>
@interface _NSPredicateOperatorUtilities : NSObject
+(id)newStringFrom:(id)arg1 usingUnicodeTransforms:(unsigned)arg2 ;
+(CFLocaleRef)retainedLocale;
+(char)doRegexForString:(id)arg1 pattern:(id)arg2 likeProtect:(char)arg3 flags:(unsigned)arg4 context:(SCD_Struct_NS51*)arg5 ;
+(long)copyRegexFindSafePattern:(id)arg1 toBuffer:(unsigned short*)arg2 ;
@end

