/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:20:55 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/Foundation.framework/Foundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Foundation/Foundation-Structs.h>
#import <Foundation/NSIndexSet.h>

@interface _NSPlaceholderIndexSet : NSIndexSet
-(id)initWithIndexSet:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)retain;
-(oneway void)release;
-(unsigned)retainCount;
-(id)initWithIndexesInRange:(NSRange)arg1 ;
@end

