/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:20:57 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/Foundation.framework/Foundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@interface NSFilePresenterAsynchronousOperation : NSOperation {

	/*^block*/id _block;
	char _isFinished;
	char _isExecuting;

}
+(id)operationWithBlock:(/*^block*/id)arg1 ;
-(char)isAsynchronous;
-(void)start;
-(char)isFinished;
-(char)isExecuting;
-(void)finish;
@end

