/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:20:55 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/Foundation.framework/Foundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Foundation/Foundation-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@interface NSIndexPath : NSObject <NSCopying, NSSecureCoding> {

	unsigned* _indexes;
	unsigned _length;
	void* _reserved;

}

@property (readonly) unsigned length; 
+(id)indexPath;
+(char)supportsSecureCoding;
+(id)indexPathWithIndex:(unsigned)arg1 ;
+(id)indexPathWithIndexes:(const unsigned*)arg1 length:(unsigned)arg2 ;
-(void)getIndexes:(unsigned*)arg1 range:(NSRange)arg2 ;
-(void)getIndexes:(unsigned*)arg1 ;
-(id)initWithIndexes:(const unsigned*)arg1 length:(unsigned)arg2 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(int)compare:(id)arg1 ;
-(unsigned)length;
-(id)copyWithZone:(NSZone*)arg1 ;
-(unsigned)indexAtPosition:(unsigned)arg1 ;
-(id)indexPathByAddingIndex:(unsigned)arg1 ;
-(id)indexPathByRemovingLastIndex;
-(id)initWithIndex:(unsigned)arg1 ;
@end

