/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:07 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PSPasscodeFieldDelegate <NSObject>
@optional
-(id)passcodeField:(id)arg1 shouldInsertText:(id)arg2;

@required
-(void)passcodeField:(id)arg1 enteredPasscode:(id)arg2;

@end

