/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:07 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface PSSystemPolicyManager : NSObject
+(void)_populateBBSectionIDs;
+(char)_shouldIncludeProxy:(id)arg1 ;
+(char)_systemSettingsNeededForProxy:(id)arg1 ;
+(char)_privacySettingsNeededForProxy:(id)arg1 ;
+(char)_locationSettingsNeededForBundleID:(id)arg1 ;
+(char)_backgroundAppRefreshSettingsNeededForProxy:(id)arg1 ;
+(char)_cellularDataSettingsNeededForBundleID:(id)arg1 ;
+(char)_notificationSettingsNeededForBundleID:(id)arg1 ;
+(id)_dataUsageWorkspaceInfo;
+(id)thirdPartyApplicationProxies;
+(id)thirdPartyApplicationProxyForBundleID:(id)arg1 ;
@end

