/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:49 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CorePrediction.framework/CorePrediction
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSObject;

@interface CPMLEvalutionResult : NSObject {

	NSObject* object;
	unsigned count;

}
-(id)init:(id)arg1 withConfigurationList:(id)arg2 ;
-(id)getString;
-(id)getStringList;
-(double)getDouble;
-(int)getInt;
-(id)getList;
-(id)getListDict;
@end

