/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:30:27 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/MapKit.framework/MapKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MapKit/MKOverlayPathView.h>

@class MKCircle;

@interface MKCircleView : MKOverlayPathView

@property (nonatomic,readonly) MKCircle * circle; 
-(MKCircle *)circle;
-(id)initWithCircle:(id)arg1 ;
-(void)createPath;
@end

