/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:30:29 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/MapKit.framework/MapKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface MKTransitDepartureFrequencyFormatter : NSObject
+(id)descriptionForFrequencyMinuteValue:(int)arg1 ;
+(id)formattedDescriptionForFrequency:(id)arg1 ;
+(char)_componentsWillUseShortFormat:(id)arg1 ;
+(id)descriptionForFrequencyRangeWithMinFrequency:(int)arg1 maxFrequency:(int)arg2 ;
+(id)_frequencyStringForComponents:(id)arg1 forRange:(char)arg2 forceShort:(char)arg3 ;
@end

