/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:16:41 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/HealthKitUI.framework/HealthKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface _HKHorizontalSingleLineSeriesMarkEntry : NSObject {

	float _xCoord;
	int _markStyle;

}

@property (nonatomic,readonly) float xCoord;               //@synthesize xCoord=_xCoord - In the implementation block
@property (nonatomic,readonly) int markStyle;              //@synthesize markStyle=_markStyle - In the implementation block
-(int)markStyle;
-(id)initWithXCoord:(float)arg1 markStyle:(int)arg2 ;
-(float)xCoord;
@end

