/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:05 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/PowerlogHelperdOperators.framework/PowerlogHelperdOperators
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

typedef struct IONotificationPort* IONotificationPortRef;

typedef struct __NStatSource* NStatSourceRef;

typedef struct __NStatManager* NStatManagerRef;

typedef struct __IOHIDEventSystemClient* IOHIDEventSystemClientRef;

typedef struct ggcontext* ggcontextRef;

