/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:19:16 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface NSGlyphGenerator : NSObject
+(void)initialize;
+(id)defaultGlyphGenerator;
+(id)sharedGlyphGenerator;
-(void)generateGlyphsForGlyphStorage:(id)arg1 desiredNumberOfCharacters:(unsigned)arg2 glyphIndex:(unsigned*)arg3 characterIndex:(unsigned*)arg4 ;
@end

