/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:19:01 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol CUIKSingleDayTimelineGeometryDelegate <NSObject>
@property (nonatomic,readonly) CGRect displayedRect; 
@property (nonatomic,readonly) float hourHeight; 
@property (nonatomic,readonly) float topPadding; 
@property (nonatomic,readonly) float timeWidth; 
@property (nonatomic,readonly) char originIsUpperLeft; 
@required
-(CGPoint*)pointForDate:(double)arg1;
-(double)dateForPoint:(CGPoint)arg1;
-(float)hourHeight;
-(float)topPadding;
-(float)timeWidth;
-(CGRect)displayedRect;
-(char)originIsUpperLeft;

@end

