/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:19:01 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UIActivityIndicatorView;

@interface EKEventAttachmentCell : UITableViewCell {

	UIActivityIndicatorView* _activityIndicator;

}
-(id)_iconForDocumentProxy:(id)arg1 ;
-(void)showSpinner:(char)arg1 ;
-(void)layoutSubviews;
-(void)setAttachment:(id)arg1 ;
@end

