/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:19:02 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol EKUILocationSearchModelDelegate
@required
-(void)currentLocationUpdated:(id)arg1;
-(void)mapSearchUpdated:(id)arg1;
-(void)contactsSearchUpdated:(id)arg1;
-(void)recentsSearchUpdated:(id)arg1;
-(void)frequentsSearchUpdated:(id)arg1;
-(void)eventsSearchUpdated:(id)arg1;
-(id)calendarItemForSearchModel:(id)arg1;
-(void)conferenceRoomSearchUpdated:(id)arg1;
-(void)locationSearchModel:(id)arg1 selectedLocation:(id)arg2 withError:(id)arg3;

@end

