/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:19:03 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UIView;

@interface EKUIInviteesViewMessageSendingView : UIView {

	UIView* _composeView;

}

@property (nonatomic,retain) UIView * composeView;              //@synthesize composeView=_composeView - In the implementation block
-(void)setComposeView:(UIView *)arg1 ;
-(UIView *)composeView;
-(void)layoutSubviews;
@end

