/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:19:01 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MKSearchCompleterDelegate <NSObject>
@optional
-(void)completerDidFail:(id)arg1 error:(id)arg2;
-(void)completerWillAccessNetwork:(id)arg1;
-(void)completerDidAccessNetwork:(id)arg1;
-(void)completerWillUpdateResults:(id)arg1;
-(void)completerDidUpdateResults:(id)arg1 finished:(char)arg2;

@end

