/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:32:46 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol CNContactPickerDelegate <NSObject>
@optional
-(void)contactPickerDidCancel:(id)arg1;
-(void)contactPicker:(id)arg1 didSelectContact:(id)arg2;
-(void)contactPicker:(id)arg1 didSelectContactProperty:(id)arg2;
-(void)contactPicker:(id)arg1 didSelectContacts:(id)arg2;
-(void)contactPicker:(id)arg1 didSelectContactProperties:(id)arg2;

@end

