/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:32:47 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MFDragSource <NSObject>
@required
-(id)viewForDragSource;
-(id)viewForDraggedItem:(id)arg1 atScale:(float)arg2;
-(char)allowsDrag;
-(void)dragCompletedForItem:(id)arg1 success:(char)arg2;
-(CGRect*)frameForDraggedItem:(id)arg1;
-(void)dragStartedWithItem:(id)arg1;
-(void)animatePlaceholderForDragFailure:(id)arg1;
-(id)dragInitiatedAtPoint:(CGPoint)arg1;

@end

