/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:32:46 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Message/MFMailDropMailParser.h>

@interface MFMailDropMailParserUI : MFMailDropMailParser
+(id)_mailDropClassName:(id)arg1 ;
+(id)_extractElementURL:(id)arg1 ;
+(char)isMailDropClass:(id)arg1 ;
+(char)isMailDropItem:(id)arg1 ;
+(char)isMailDropBanner:(id)arg1 ;
+(id)parseElement:(id)arg1 ;
+(void)MFConvertHTMLNodeToAttachmentNode:(id)arg1 element:(id)arg2 mailDrop:(id)arg3 ;
+(void)MFConvertHTMLBannerToInvisibleAttachmentNode:(id)arg1 element:(id)arg2 mailDrop:(id)arg3 ;
@end

