/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:32:47 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UIAdaptivePresentationControllerDelegate <NSObject>
@optional
-(int)adaptivePresentationStyleForPresentationController:(id)arg1;
-(int)adaptivePresentationStyleForPresentationController:(id)arg1 traitCollection:(id)arg2;
-(void)presentationController:(id)arg1 willPresentWithAdaptiveStyle:(int)arg2 transitionCoordinator:(id)arg3;
-(id)presentationController:(id)arg1 viewControllerForAdaptivePresentationStyle:(int)arg2;

@end

