/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:14:54 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/AnnotationKit.framework/AnnotationKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol AKRectangularAnnotationProtocol <NSObject>
@property (assign) CGRect rectangle; 
@required
-(CGRect)rectangle;
-(void)setRectangle:(CGRect)arg1;

@end

