/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:14:54 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/AnnotationKit.framework/AnnotationKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol AKRotatableAnnotationProtocol <NSObject>
@property (assign) float rotationAngle; 
@required
-(float)rotationAngle;
-(void)setRotationAngle:(float)arg1;

@end

