/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:18 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/RadioUI.framework/RadioUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <RadioUI/RURadioAVItem.h>

@interface RURadioAudioClipAVItem : RURadioAVItem
+(void)initialize;
-(void)loadAssetAndPlayerItem;
-(char)supportsSkip;
-(char)isLikedStateEnabled;
-(id)artworkCatalogForPlaybackTime:(double)arg1 ;
-(unsigned)type;
-(char)_canUseStoreAdamIDForSubscriptionAdamID;
-(id)audioClip;
-(id)initWithAudioClip:(id)arg1 ;
@end

