/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:16:30 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <GeoServices/GeoServices-Structs.h>
@class GEOTransitRouteMatcher, GEOComposedRoute, GEOMapAccess, GEOMotionContext;

@interface _GEORouteMatchUpdater : NSObject {

	GEOTransitRouteMatcher* _routeMatcher;
	GEOComposedRoute* _route;
	GEOMapAccess* _mapAccess;
	GEOMotionContext* _motionContext;
	double _stationRadius;

}
-(void)dealloc;
-(unsigned)priority;
-(char)updateRouteMatch:(id)arg1 previousRouteMatch:(id)arg2 forLocation:(id)arg3 ;
-(char)_isLocation:(id)arg1 nearStation:(id)arg2 ;
-(char)_isLocation:(id)arg1 nearStop:(id)arg2 ;
-(double)_stationRadiusForStation:(id)arg1 accessPoint:(id)arg2 adjacentWalkingLegCoordinate:(SCD_Struct_GE16)arg3 ;
-(id)initWithTransitRouteMatcher:(id)arg1 ;
-(char)_isLocation:(id)arg1 nearTransitPoint:(SCD_Struct_GE16)arg2 transitID:(unsigned long long)arg3 featureSize:(double)arg4 ;
@end

