/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:16:30 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSXMLParserDelegate.h>
#import <libobjc.A.dylib/GEOResourceManifestTileGroupObserver.h>

@class GEOAltitudeManifestReserved, NSString;

@interface GEOAltitudeManifest : NSObject <NSXMLParserDelegate, GEOResourceManifestTileGroupObserver> {

	GEOAltitudeManifestReserved* _reserved;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedManager;
-(void)dealloc;
-(id)init;
-(void)commonInit;
-(void)resourceManifestManagerWillChangeActiveTileGroup:(id)arg1 ;
-(void)resourceManifestManagerDidChangeActiveTileGroup:(id)arg1 ;
-(id)nameForRegion:(unsigned)arg1 ;
-(id)initWithoutObserver;
-(id)tourIdsForRegion:(unsigned)arg1 ;
-(id)availableRegions;
-(id)tripIdsForRegion:(unsigned)arg1 ;
-(char)isValidTourId:(unsigned long long)arg1 ;
-(char)parseXml:(id)arg1 ;
-(void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5 ;
-(unsigned)versionForRegion:(unsigned)arg1 ;
-(char)hasDataVersionForRegion:(unsigned)arg1 ;
-(unsigned)dataVersionForRegion:(unsigned)arg1 ;
-(void)parseManifest:(id)arg1 ;
-(void)_reloadManifest;
@end

