/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:16:33 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol GEOCategorySuggestionsManagerServerProxy;
@interface GEOCategorySuggestionsManager : NSObject {

	id<GEOCategorySuggestionsManagerServerProxy> _serverProxy;

}
+(id)sharedManager;
+(void)setUseLocalProxy:(char)arg1 ;
-(void)dealloc;
-(id)init;
-(void)updateCachedSpotlightCategorySuggestions:(/*^block*/id)arg1 ;
-(void)fetchSpotlightCategorySuggestions:(/*^block*/id)arg1 ;
-(id)_spotlightCategorySuggestionsForResponse:(id)arg1 ;
@end

