/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:31:42 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MPMovieViewDelegate <NSObject>
@optional
-(void)movieView:(id)arg1 willMoveToWindow:(id)arg2;
-(void)movieViewDidMoveToWindow:(id)arg1;
-(void)movieView:(id)arg1 willMoveToSuperview:(id)arg2;

@end

