/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:31:45 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MPQueueFeederDelegate <NSObject>
@required
-(void)queueFeeder:(id)arg1 didChangeContentsWithPreferredStartIndex:(unsigned)arg2 error:(id)arg3;
-(void)queueFeeder:(id)arg1 didChangeContentsWithReplacementPlaybackContext:(id)arg2;
-(void)queueFeederDidInvalidateAssets:(id)arg1;

@end

