/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:31:42 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface MPUITransitionViewRunner : NSObject
+(void)performTransition:(int)arg1 withTransitionView:(id)arg2 fromViewController:(id)arg3 toViewController:(id)arg4 completion:(/*^block*/id)arg5 ;
+(id)sharedInstance;
-(void)transitionViewDidComplete:(id)arg1 fromView:(id)arg2 toView:(id)arg3 ;
@end

