/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:50:52 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/WatchConnectivity.framework/WatchConnectivity
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol WCXPCPrivateManagerClientProtocol <NSObject>
@required
-(void)handlePingForExtensionBundleID:(id)arg1;
-(void)isExtensionPrivileged:(id)arg1 completionHandler:(/*^block*/id)arg2;

@end

