/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:25 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/NanoAppRegistry.framework/Support/nanoappregistryd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NADAppSerializer, NSFileManager, NSURL;

@interface NADEntityStore : NSObject {

	/*^block*/id _identifierBlock;
	NADAppSerializer* _serializer;
	NSFileManager* _fileManager;
	NSURL* _directory;

}

@property (nonatomic,readonly) NSURL * directory;              //@synthesize directory=_directory - In the implementation block
-(id)initWithDirectory:(id)arg1 serializer:(id)arg2 identifierBlock:(/*^block*/id)arg3 ;
-(void)addEntity:(id)arg1 ;
-(id)allEntities;
-(void)clearStore;
-(void)removeEntity:(id)arg1 ;
-(void)_createDirectoryIfNeeded;
-(id)directoryForEntity:(id)arg1 ;
-(NSURL *)directory;
@end

