/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 4:20:34 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PKModularService <NSObject>
@optional
-(void)beginUsing:(id)arg1 withBundle:(id)arg2;
-(void)endUsing:(id)arg1;
-(void)communicationsFailed:(id)arg1;

@required
+(id)initForPlugInKit;

@end

