/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:14:32 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/CoreText.framework/CoreText
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreText/NSRubyAnnotation.h>

@interface NSCTRubyAnnotation : NSRubyAnnotation
+(Class)classForKeyedArchiver;
+(Class)classForKeyedUnarchiver;
-(unsigned long)_cfTypeID;
-(char)isEqual:(id)arg1 ;
-(id)retain;
-(oneway void)release;
-(unsigned)retainCount;
-(unsigned)hash;
-(char)allowsWeakReference;
-(char)retainWeakReference;
-(void)finalize;
@end

