/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:14:48 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/Accessibility.framework/Frameworks/AXSpringBoardServerInstance.framework/AXSpringBoardServerInstance
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AXSpringBoardServerInstance/__AXSBPassKitPrearmTriggerAccessibility_super.h>

@interface AXSBPassKitPrearmTriggerAccessibility : __AXSBPassKitPrearmTriggerAccessibility_super
+(Class)safeCategoryBaseClass;
+(id)safeCategoryTargetClassName;
+(void)_accessibilityPerformValidations:(id)arg1 ;
-(void)dealloc;
-(char)_accessibilityRegisteredForHomeClickPrefNotifications;
-(void)_accessibilitySetRegisteredForHomeClickPrefNotifications:(char)arg1 ;
-(id)initWithDelegate:(id)arg1 fingerDownTimeout:(double)arg2 menuPressTimeout:(double)arg3 ;
-(void)accessibilityRegisterForHomeClickPrefNotifications;
@end

