/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:32 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/Search.framework/searchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

typedef struct __MDSimpleQueryEvaluator* MDSimpleQueryEvaluatorRef;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct __SI* SIRef;

typedef struct __SIResultQueue* SIResultQueueRef;

typedef struct __SIJobRef* SIJobRefRef;

typedef struct __CFArray* CFArrayRef;

