/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:16:42 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/HelpKit.framework/HelpKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface HLPHelpUsageController : NSObject {

	NSString* _identifier;
	NSString* _version;

}
-(void)increaseUsageCountForKey:(id)arg1 ;
-(id)initWithIndentifier:(id)arg1 version:(id)arg2 ;
@end

