/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 4:17:35 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/Accounts.framework/Accounts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Accounts/Accounts-Structs.h>
#import <libobjc.A.dylib/NSSecureCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@class ACAccountStore, NSString, ACAccountType, ACAccountCredential, NSMutableDictionary, NSURL, NSDate, NSArray, NSMutableSet, NSDictionary, NSSet;

@interface ACAccount : NSObject <NSSecureCoding, NSCopying> {

	ACAccountStore* _store;
	NSString* _identifier;
	NSString* _accountDescription;
	NSString* _owningBundleID;
	NSString* _username;
	NSString* _authenticationType;
	NSString* _credentialType;
	NSString* _clientToken;
	char _haveCheckedForClientToken;
	ACAccountType* _accountType;
	ACAccountCredential* _credential;
	NSMutableDictionary* _properties;
	NSMutableDictionary* _dataclassProperties;
	char _accountAccessAvailable;
	char _authenticated;
	char _active;
	char _supportsAuthentication;
	char _visible;
	NSURL* _objectID;
	NSDate* _date;
	NSDate* _lastCredentialRenewalRejectionDate;
	ACAccount* _parentAccount;
	char _haveCheckedForParentAccount;
	NSString* _parentAccountIdentifier;
	char _haveCheckedForChildAccounts;
	NSArray* _childAccounts;
	NSMutableSet* _enabledDataclasses;
	NSMutableSet* _provisionedDataclasses;
	NSMutableSet* _dirtyProperties;
	NSMutableSet* _dirtyAccountProperties;
	NSMutableSet* _dirtyDataclassProperties;
	id _credentialsDidChangeObserver;
	/*^block*/id _accountPropertiesTransformer;
	char _creatingFromManagedObject;

}

@property (nonatomic,__weak,readonly) NSString * identifier; 
@property (nonatomic,retain) ACAccountType * accountType; 
@property (nonatomic,copy) NSString * accountDescription; 
@property (nonatomic,copy) NSString * username; 
@property (nonatomic,readonly) NSString * userFullName; 
@property (nonatomic,retain) ACAccountCredential * credential; 
@property (nonatomic,readonly) NSURL * objectID; 
@property (nonatomic,readonly) ACAccountStore * accountStore; 
@property (nonatomic,retain) ACAccount * parentAccount; 
@property (nonatomic,readonly) NSString * parentAccountIdentifier; 
@property (nonatomic,readonly) NSArray * childAccounts; 
@property (nonatomic,retain) NSMutableSet * enabledDataclasses; 
@property (nonatomic,retain) NSMutableSet * provisionedDataclasses; 
@property (nonatomic,__weak,readonly) NSDictionary * dataclassProperties; 
@property (assign,getter=isAuthenticated,nonatomic) char authenticated; 
@property (nonatomic,__weak,readonly) NSDictionary * accountProperties; 
@property (nonatomic,__weak,readonly) ACAccount * displayAccount; 
@property (assign,getter=isActive,nonatomic) char active; 
@property (assign,nonatomic) char supportsAuthentication; 
@property (getter=isDirty,nonatomic,readonly) char dirty; 
@property (nonatomic,readonly) NSSet * dirtyProperties;                                //@synthesize dirtyProperties=_dirtyProperties - In the implementation block
@property (nonatomic,readonly) NSSet * dirtyAccountProperties;                         //@synthesize dirtyAccountProperties=_dirtyAccountProperties - In the implementation block
@property (nonatomic,readonly) NSSet * dirtyDataclassProperties;                       //@synthesize dirtyDataclassProperties=_dirtyDataclassProperties - In the implementation block
@property (nonatomic,readonly) NSString * authenticationType; 
@property (nonatomic,readonly) NSString * credentialType; 
@property (nonatomic,readonly) char supportsPush; 
@property (nonatomic,retain) NSDate * creationDate; 
@property (assign,getter=isVisible,nonatomic) char visible; 
@property (nonatomic,retain) NSDate * lastCredentialRenewalRejectionDate; 
@property (nonatomic,readonly) NSString * shortDebugName; 
@property (nonatomic,readonly) NSString * clientToken; 
@property (copy) id accountPropertiesTransformer;                                      //@synthesize accountPropertiesTransformer=_accountPropertiesTransformer - In the implementation block
+(id)_createNewAccountUID;
+(char)supportsSecureCoding;
-(void)_clearCachedChildAccounts;
-(void)_clearDirtyProperties;
-(void)_clearCachedCredentials;
-(void)_installCredentialsChangedObserver;
-(void)_markPropertyDirty:(id)arg1 ;
-(void)credentialsChanged:(id)arg1 ;
-(id)accountPropertiesTransformer;
-(void)_markAccountPropertyDirty:(id)arg1 ;
-(id)enabledAndSyncableDataclasses;
-(char)_useParentForCredentials;
-(void)_markDataclassPropertyDirty:(id)arg1 ;
-(void)_markCredentialDirty;
-(void)setAccountProperties:(NSDictionary *)arg1 ;
-(id)qualifiedUsername;
-(id)defaultAutodiscoverDomainForChildType:(id)arg1 ;
-(void)setCreatingFromManagedObject:(char)arg1 ;
-(NSString *)shortDebugName;
-(void)setSecIdentity:(SecIdentityRef)arg1 ;
-(void)setSecCertificates:(id)arg1 ;
-(void)setAccountPropertiesTransformer:(id)arg1 ;
-(NSSet *)dirtyProperties;
-(char)isPropertyDirty:(id)arg1 ;
-(void)_setObjectID:(id)arg1 ;
-(ACAccount *)displayAccount;
-(id)accountPropertyForKey:(id)arg1 ;
-(NSString *)userFullName;
-(id)propertyForKey:(id)arg1 ;
-(void)setProperty:(id)arg1 forKey:(id)arg2 ;
-(ACAccountStore *)accountStore;
-(void)setAccountDescription:(NSString *)arg1 ;
-(NSString *)credentialType;
-(void)setCredential:(ACAccountCredential *)arg1 ;
-(char)isEnabledForDataclass:(id)arg1 ;
-(NSDate *)creationDate;
-(void)setCreationDate:(NSDate *)arg1 ;
-(NSURL *)objectID;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)description;
-(void)reload;
-(id)objectForKeyedSubscript:(id)arg1 ;
-(void)setObject:(id)arg1 forKeyedSubscript:(id)arg2 ;
-(char)isActive;
-(NSString *)identifier;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setIdentifier:(NSString *)arg1 ;
-(void)setVisible:(char)arg1 ;
-(void)setActive:(char)arg1 ;
-(char)isVisible;
-(id)initWithManagedAccount:(id)arg1 ;
-(id)owningBundleID;
-(void)setOwningBundleID:(id)arg1 ;
-(id)initWithManagedAccount:(id)arg1 accountStore:(id)arg2 ;
-(void)_loadAllCachedProperties;
-(void)_setAccountStore:(id)arg1 ;
-(NSSet *)dirtyDataclassProperties;
-(id)_initWithManagedAccount:(id)arg1 accountStore:(id)arg2 withDirtyStateFromAccount:(id)arg3 ;
-(id)diffAccount:(id)arg1 ;
-(NSSet *)dirtyAccountProperties;
-(void)setDataclassProperties:(NSDictionary *)arg1 ;
-(void)setEnabledDataclasses:(NSMutableSet *)arg1 ;
-(void)markAllPropertiesDirty;
-(void)setLastCredentialRenewalRejectionDate:(NSDate *)arg1 ;
-(void)_loadCachedPropertiesWithoutCredentials;
-(id)accountByCleaningThirdPartyTransformations;
-(NSDate *)lastCredentialRenewalRejectionDate;
-(void)setProperties:(id)arg1 forDataclass:(id)arg2 ;
-(ACAccountType *)accountType;
-(NSArray *)childAccounts;
-(id)initWithAccountType:(id)arg1 ;
-(void)setParentAccount:(ACAccount *)arg1 ;
-(ACAccount *)parentAccount;
-(SecIdentityRef)copySecIdentity;
-(id)secCertificates;
-(char)authenticated;
-(char)isEnabledToSyncDataclass:(id)arg1 ;
-(char)addClientToken:(id)arg1 ;
-(void)takeValuesFromModifiedAccount:(id)arg1 ;
-(char)supportsPush;
-(NSMutableSet *)provisionedDataclasses;
-(ACAccountCredential *)credential;
-(id)fullDescription;
-(NSString *)authenticationType;
-(void)setAuthenticationType:(NSString *)arg1 ;
-(NSString *)clientToken;
-(void)setProvisionedDataclasses:(NSMutableSet *)arg1 ;
-(void)setAuthenticated:(char)arg1 ;
-(NSString *)parentAccountIdentifier;
-(NSDictionary *)accountProperties;
-(void)setAccountProperty:(id)arg1 forKey:(id)arg2 ;
-(id)credentialWithError:(id*)arg1 ;
-(NSMutableSet *)enabledDataclasses;
-(id)childAccountsWithAccountTypeIdentifier:(id)arg1 ;
-(NSDictionary *)dataclassProperties;
-(void)setCredentialType:(NSString *)arg1 ;
-(void)setEnabled:(char)arg1 forDataclass:(id)arg2 ;
-(id)propertiesForDataclass:(id)arg1 ;
-(char)isProvisionedForDataclass:(id)arg1 ;
-(char)isDirty;
-(char)supportsAuthentication;
-(void)setSupportsAuthentication:(char)arg1 ;
-(void)setUsername:(NSString *)arg1 ;
-(NSString *)accountDescription;
-(NSString *)username;
-(void)refresh;
-(char)isAuthenticated;
-(void)setAccountType:(ACAccountType *)arg1 ;
@end

