/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 4:17:35 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/Accounts.framework/Accounts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol NSCopying
@required
-(id)copyWithZone:(NSZone*)arg1;

@end

