/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:28 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/NanoPassKit.framework/NanoPassKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <NanoPassKit/NanoPassKit-Structs.h>
#import <ProtocolBuffer/PBRequest.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData;

@interface NPKProtoSignDataRequest : PBRequest <NSCopying> {

	NSData* _dataToSign;
	NSData* _digestToSign;

}

@property (nonatomic,readonly) char hasDataToSign; 
@property (nonatomic,retain) NSData * dataToSign;                 //@synthesize dataToSign=_dataToSign - In the implementation block
@property (nonatomic,readonly) char hasDigestToSign; 
@property (nonatomic,retain) NSData * digestToSign;               //@synthesize digestToSign=_digestToSign - In the implementation block
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(void)copyTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)setDataToSign:(NSData *)arg1 ;
-(void)setDigestToSign:(NSData *)arg1 ;
-(char)hasDataToSign;
-(char)hasDigestToSign;
-(NSData *)dataToSign;
-(NSData *)digestToSign;
-(char)readFrom:(id)arg1 ;
@end

