/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:19:06 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/TCC.framework/tccd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libobjc.A.dylib/SYObject.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSString;

@interface TCCDSyncAccessAction : NSObject <SYObject, NSSecureCoding> {

	NSString* _serviceIdentifier;
	long long _versionNumber;

}

@property (readonly) NSString * serviceIdentifier;                  //@synthesize serviceIdentifier=_serviceIdentifier - In the implementation block
@property (assign) long long versionNumber;                         //@synthesize versionNumber=_versionNumber - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)supportsSecureCoding;
-(void)updateDatabase:(unsigned)arg1 killClient:(char)arg2 ;
-(void)setVersionNumber:(long long)arg1 ;
-(long long)versionNumber;
-(NSString *)serviceIdentifier;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(unsigned)hash;
-(NSString *)description;
-(id)_description;
-(id)syncId;
-(id)initWithServiceIdentifier:(id)arg1 ;
@end

