/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:27:33 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/_UIDocumentPickerCell.h>

@interface _UIDocumentPickerDocumentCell : _UIDocumentPickerCell {

	char _enabled;

}

@property (assign,nonatomic) char enabled;              //@synthesize enabled=_enabled - In the implementation block
-(char)enabled;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)setEnabled:(char)arg1 ;
-(void)prepareForReuse;
-(void)_showPickableDiagnostic;
-(void)reloadItem:(char)arg1 ;
-(void)updateContents;
-(void)updateThumbnail;
@end

