/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:27:37 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol _UIFocusScrollAnimator <NSObject>
@property (assign,nonatomic) float defaultConvergenceRate; 
@property (nonatomic,readonly) char requiresExtendingScrollViewVisibleBounds; 
@required
-(void)setDefaultConvergenceRate:(float)arg1;
-(char)isAnimatingScrollView:(id)arg1;
-(void)cancelScrollingForScrollView:(id)arg1;
-(char)requiresExtendingScrollViewVisibleBounds;
-(void)cancelPeekAdjustmentForScrollView:(id)arg1 performRollback:(char)arg2;
-(void)setPeekOffsetAdjustment:(CGPoint)arg1 forScrollView:(id)arg2;
-(void)setTargetContentOffset:(CGPoint)arg1 forScrollView:(id)arg2 convergenceRate:(float)arg3 completion:(/*^block*/id)arg4;
-(float)defaultConvergenceRate;

@end

