/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:27:40 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class UITextInputController;

@interface _UITextInputControllerLayoutManagerConnection : NSObject {

	UITextInputController* _textInputController;

}

@property (nonatomic,retain) UITextInputController * textInputController;              //@synthesize textInputController=_textInputController - In the implementation block
-(void)dealloc;
-(id)initWithTextInputController:(id)arg1 ;
-(UITextInputController *)textInputController;
-(void)setTextInputController:(UITextInputController *)arg1 ;
@end

