/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:27:23 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class UIResponder;

@interface _UITouchForwardingRecipient : NSObject {

	int recordedPhase;
	int autocompletedPhase;
	UIResponder* fromResponder;
	UIResponder* responder;

}

@property (assign,nonatomic,__weak) UIResponder * fromResponder; 
@property (assign,nonatomic,__weak) UIResponder * responder; 
@property (assign,nonatomic) int recordedPhase; 
@property (assign,nonatomic) int autocompletedPhase; 
-(id)description;
-(void)setResponder:(UIResponder *)arg1 ;
-(UIResponder *)responder;
-(int)recordedPhase;
-(int)autocompletedPhase;
-(void)setRecordedPhase:(int)arg1 ;
-(void)setAutocompletedPhase:(int)arg1 ;
-(id)initWithResponder:(id)arg1 fromResponder:(id)arg2 ;
-(UIResponder *)fromResponder;
-(void)setFromResponder:(UIResponder *)arg1 ;
@end

