/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:27:25 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class UIView;


@protocol UIFocusContainer <NSObject>
@property (nonatomic,readonly) id<UIFocusContainer> preferredFocusedItem; 
@property (nonatomic,readonly) UIView * focusedView; 
@required
-(UIView *)focusedView;
-(void)setNeedsPreferredFocusedItemUpdate;
-(void)updatePreferredFocusedItemIfNeeded;
-(char)isAncestorOfItem:(id)arg1;
-(id<UIFocusContainer>)preferredFocusedItem;
-(char)shouldChangeFocusedItem:(id)arg1 heading:(unsigned)arg2;
-(void)focusedViewWillChange;
-(void)focusedViewDidChange;
-(char)shouldChangeFocusedItem:(id)arg1;

@end

