/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:27:16 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UIInteractionProgressObserver <NSObject>
@optional
-(void)interactionProgressDidUpdate:(id)arg1;
-(void)interactionProgress:(id)arg1 didEnd:(char)arg2;

@end

