/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:27:26 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKBRenderFactory.h>

@interface UIKBRenderFactory_Emoji : UIKBRenderFactory
-(id)backgroundTraitsForKeyplane:(id)arg1 ;
-(id)defaultKeyBackgroundColorName;
-(id)controlKeyBackgroundColorName;
-(id)_emojiDefaultControlKeyActiveBackgroundColorGradient;
-(id)_emojiDefaultControlKeyBackgroundColorGradient;
-(id)_emojiSpaceKeyActiveBackgroundColorGradient;
-(id)_emojiSpaceKeyBackgroundColorGradient;
-(id)_emojiCategoryControlKeyActiveTraits;
-(id)_emojiBorderColor;
-(id)_emojiSkinToneDividerColor;
@end

