/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:27:26 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIKit/UIKBRenderFactory_Emoji.h>

@interface UIKBRenderFactoryEmoji_iPhone : UIKBRenderFactory_Emoji
-(id)traitsHashStringForKey:(id)arg1 withGeometry:(id)arg2 controlOpacities:(char)arg3 ;
-(id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2 ;
-(float)emojiInternationalKeySize;
-(CGPoint)emojiInternationalKeyOffset;
-(CGPoint)emojiPopupTextOffset;
-(char)shouldClearBaseDisplayStringForVariants:(id)arg1 ;
@end

