/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:27:37 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface UIKeyboardEmojiCategoryController : NSObject {

	int _currentCategory;

}
+(Class)classForCategoryControl;
-(id)initWithCategoryControl:(id)arg1 ;
-(void)setCurrentCategory:(int)arg1 ;
-(int)sectionWithOffsetPercentage:(float)arg1 ;
@end

