/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:27:35 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIKit/UIKeyboardMenuView.h>

@class NSMutableArray;

@interface UIKeyboardSplitControlMenu : UIKeyboardMenuView {

	NSMutableArray* m_menuOptions;
	CGSize m_preferredSize;
	/*^block*/id _finishSplitTransitionBlock;

}

@property (nonatomic,copy) id finishSplitTransitionBlock;              //@synthesize finishSplitTransitionBlock=_finishSplitTransitionBlock - In the implementation block
+(id)sharedInstance;
+(id)activeInstance;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setSplitAndUndocked:(char)arg1 ;
-(unsigned)numberOfItems;
-(void)didFinishSplitTransition;
-(CGSize)preferredSize;
-(unsigned)defaultSelectedIndex;
-(void)didSelectItemAtIndex:(unsigned)arg1 ;
-(id)titleForItemAtIndex:(unsigned)arg1 ;
-(void)setFinishSplitTransitionBlock:(id)arg1 ;
-(id)finishSplitTransitionBlock;
@end

