/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 16, 2015 at 11:27:41 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSDictionary;

@interface UITraitCollection : NSObject <NSCopying, NSSecureCoding> {

	SCD_Struct_UI95 _builtinTraits;
	NSDictionary* _clientDefinedTraits;

}

@property (nonatomic,readonly) int barMetrics; 
@property (nonatomic,readonly) int barPosition; 
@property (nonatomic,readonly) int userInterfaceIdiom; 
@property (nonatomic,readonly) float displayScale; 
@property (nonatomic,readonly) int horizontalSizeClass; 
@property (nonatomic,readonly) int verticalSizeClass; 
@property (nonatomic,readonly) int forceTouchCapability; 
+(char)supportsSecureCoding;
+(id)traitCollectionWithDisplayScale:(float)arg1 ;
+(id)traitCollectionWithHorizontalSizeClass:(int)arg1 ;
+(id)traitCollectionWithVerticalSizeClass:(int)arg1 ;
+(id)traitCollectionWithTraitsFromCollections:(id)arg1 ;
+(id)_emptyTraitCollection;
+(id)traitCollectionWithUserInterfaceIdiom:(int)arg1 ;
+(id)traitCollectionWithInteractionModel:(unsigned)arg1 ;
+(id)traitCollectionWithTouchLevel:(int)arg1 ;
+(id)traitCollectionWithUserInterfaceStyle:(int)arg1 ;
+(id)traitCollectionWithForceTouchCapability:(int)arg1 ;
+(id)_traitCollectionWithValue:(id)arg1 forTraitNamed:(id)arg2 ;
+(id)traitCollectionWithBarMetrics:(int)arg1 ;
+(id)traitCollectionWithBarPosition:(int)arg1 ;
-(int)userInterfaceIdiom;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(int)verticalSizeClass;
-(int)horizontalSizeClass;
-(unsigned)interactionModel;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)_initWithBuiltinTraitStorage:(SCD_Struct_UI95*)arg1 clientDefinedTraits:(id)arg2 ;
-(float)displayScale;
-(char)containsTraitsInCollection:(id)arg1 ;
-(int)barMetrics;
-(int)barPosition;
-(int)userInterfaceStyle;
-(id)_valueForTraitNamed:(id)arg1 ;
-(int)_compare:(id)arg1 ;
-(id)_namedImageDescription;
-(char)_matchesIntersectionWithTraitCollection:(id)arg1 ;
-(int)touchLevel;
-(int)forceTouchCapability;
@end

