/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:41 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class EDResources;

@interface CHDLegendEntry : NSObject {

	unsigned mFontIndex;
	unsigned mEntryIndex;
	EDResources* mResources;

}
-(void)dealloc;
-(id)description;
-(void)setFont:(id)arg1 ;
-(id)font;
-(void)setFontIndex:(unsigned)arg1 ;
-(id)initWithResources:(id)arg1 ;
-(void)setEntryIndex:(unsigned)arg1 ;
-(unsigned)fontIndex;
-(unsigned)entryIndex;
@end

