/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:38 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/CXNamespace.h>

@interface CXUnqualifiedNamespace : CXNamespace
-(char)containsNode:(xmlNode*)arg1 ;
-(id)initWithUri:(const char*)arg1 ;
-(char)containsAttribute:(xmlAttr*)arg1 ;
@end

