/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:42 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <OfficeImport/OfficeImport-Structs.h>
@class EDWorkbook, EDWorksheet, EDCollection, EDReference, EDRowBlocks, EDRowBlock;

@interface EDReferenceIterator : NSObject {

	EDWorkbook* mWorkbook;
	EDWorksheet* mCurrentSheet;
	EDCollection* mReferences;
	EDReference* mReference;
	EDRowBlocks* mRowBlocks;
	EDRowBlock* mRowBlock;
	unsigned mRowBlockIndex;
	EDRowInfo* mRowInfo;
	unsigned mRowInfoIndex;
	unsigned mCellIndex;
	unsigned mNextArrayIndex;
	int mCurrentCellIndex;
	unsigned mPreviousColumnNumber;

}
+(id)referenceIteratorWithReferenceArray:(id)arg1 workbook:(id)arg2 ;
+(id)referenceIteratorWithReference:(id)arg1 workbook:(id)arg2 ;
-(void)dealloc;
-(void)setCurrentSheet:(id)arg1 ;
-(EDCellHeader*)nextCell;
-(unsigned)currentCellIndex;
-(void)setReference:(id)arg1 ;
-(id)initWithReferenceArray:(id)arg1 reference:(id)arg2 workbook:(id)arg3 ;
-(id)initWithReference:(id)arg1 workbook:(id)arg2 ;
-(id)initWithReferenceArray:(id)arg1 workbook:(id)arg2 ;
-(BOOL)nextRow;
-(BOOL)nextReference;
@end

