/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:42 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface EDTokenTree : NSObject
+(id)buildSubtreeAtIndex:(unsigned*)arg1 formula:(id)arg2 ;
+(id)buildSubtree:(unsigned)arg1 formula:(id)arg2 ;
+(unsigned)childCountForToken:(unsigned)arg1 formula:(id)arg2 ;
+(BOOL)isTokenNoOp:(unsigned)arg1 formula:(id)arg2 ;
+(BOOL)isTokenAttrASum:(unsigned short)arg1 ;
@end

