/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:42 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol EFHelper <NSObject>
@required
-(int)rowNumber;
-(unsigned)resolveFile:(id)arg1;
-(unsigned)resolveTableColumn:(id)arg1 columnName:(id)arg2;
-(int)resolveFunctionName:(id)arg1;
-(int)columnNumber;
-(unsigned)resolveName:(id)arg1;
-(unsigned)resolveSheet:(id)arg1;
-(char)isCurrentSheet:(id)arg1;
-(unsigned)resolveFirstSheet:(id)arg1 lastSheet:(id)arg2;
-(id)resolveTable:(id)arg1;
-(unsigned)resolveTableToSheetId:(id)arg1;

@end

