/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:38 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface OABDrawing : NSObject
+(void)applyRulesFromSolverContainer:(id)arg1 state:(id)arg2 ;
+(id)readDrawablesFromDrawing:(id)arg1 state:(id)arg2 ;
+(id)readBackgroundPropertiesFromDrawing:(id)arg1 state:(id)arg2 ;
+(unsigned long)addShapeIdForObject:(id)arg1 ;
@end

