/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:39 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface OADShapeGeometry : NSObject {

	char mIsEscher;
	NSMutableDictionary* mAdjustValues;

}
-(void)dealloc;
-(id)init;
-(id)description;
-(int)type;
-(id)adjustValues;
-(id)equivalentCustomGeometry;
-(char)isEscher;
-(long)adjustValueAtIndex:(unsigned)arg1 ;
-(void)setIsEscher:(char)arg1 ;
-(unsigned)adjustValueCount;
-(char)hasAdjustValueAtIndex:(unsigned)arg1 ;
-(void)setAdjustValue:(long)arg1 atIndex:(unsigned)arg2 ;
@end

