/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:40 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <OfficeImport/ODICycle5.h>

@interface ODIGear1 : ODICycle5
+(unsigned)nodeCountWithState:(id)arg1 ;
+(void)mapStyleForTransition:(id)arg1 shape:(id)arg2 state:(id)arg3 ;
@end

