/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:40 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <OfficeImport/OfficeImport-Structs.h>
@interface ODIVenn : NSObject
+(void)mapWithState:(id)arg1 ;
+(char)mapIdentifier:(id)arg1 state:(id)arg2 ;
+(unsigned)nodeCountWithState:(id)arg1 ;
+(CGRect)mapGSpaceWithState:(id)arg1 ;
+(void)mapNode:(id)arg1 index:(unsigned)arg2 state:(id)arg3 ;
@end

