/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:37 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface OITSUBasicProgressStorage : NSObject {

	double mValue;
	double mMaxValue;
	char mIndeterminate;

}

@property (assign) double value; 
@property (assign) double maxValue; 
@property (getter=isIndeterminate) char indeterminate; 
-(double)maxValue;
-(double)value;
-(void)setValue:(double)arg1 ;
-(void)setMaxValue:(double)arg1 ;
-(char)isIndeterminate;
-(void)setIndeterminate:(char)arg1 ;
@end

