/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:25 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/NanoAudioControl.framework/NanoAudioControl
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface NACRoutingController : NSObject
+(id)localRoutingControllerWithAudioCategory:(id)arg1 ;
+(id)proxyRoutingControllerWithAudioCategory:(id)arg1 ;
+(id)companionRoutingControllerWithAudioCategory:(id)arg1 ;
@end

