/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:21 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CarKit.framework/Support/carkitd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <carkitd/CRVehicleAccessoryAlert.h>

@interface CROutstandingVehiclePairingAlert : CRVehicleAccessoryAlert {

	char _shouldEnableBluetooth;

}

@property (assign,nonatomic) char shouldEnableBluetooth;              //@synthesize shouldEnableBluetooth=_shouldEnableBluetooth - In the implementation block
-(char)presentAlertWithCompletion:(/*^block*/id)arg1 ;
-(id)_alertContents;
-(char)shouldEnableBluetooth;
-(void)setShouldEnableBluetooth:(char)arg1 ;
@end

