/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:55 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface PLCloudSpaceBudgetReservedMessage : NSObject {

	unsigned _bytes;

}

@property (nonatomic,readonly) unsigned bytes;              //@synthesize bytes=_bytes - In the implementation block
-(unsigned)bytes;
-(id)initWithBytes:(unsigned)arg1 ;
@end

