/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:56 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotoLibraryServices/PhotoLibraryServices-Structs.h>
#import <PhotoLibraryServices/PLPhotoLibrary.h>

@interface PLSharedPhotoLibrary : PLPhotoLibrary
+(id)sharedPhotoLibrary;
+(id)allocWithZone:(NSZone*)arg1 ;
-(id)init;
-(id)retain;
-(oneway void)release;
-(id)autorelease;
-(unsigned)retainCount;
-(id)copyWithZone:(NSZone*)arg1 ;
-(unsigned)concurrencyType;
-(void)_updateWithInsertedAssetsCount:(unsigned)arg1 deletedCount:(unsigned)arg2 updatedAssets:(id)arg3 ;
-(void)_assetsdHasNoXPCTransactions:(id)arg1 ;
@end

