/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:08 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MediaRemote/MediaRemote-Structs.h>
#import <MediaRemote/MRNowPlayingArtwork.h>

@interface MRNowPlayingArtworkSurface : MRNowPlayingArtwork {

	IOSurfaceRef _surface;

}

@property (nonatomic,readonly) IOSurfaceRef surface;              //@synthesize surface=_surface - In the implementation block
-(void)dealloc;
-(char)isEqual:(id)arg1 ;
-(unsigned)type;
-(IOSurfaceRef)surface;
-(id)initWithSurface:(IOSurfaceRef)arg1 ;
-(char)hasArtworkData;
-(void)bindToXPCDictionary:(id)arg1 ;
-(id)copyImageData;
@end

