/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:16 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/MobileBackup.framework/backupd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <backupd/MBServiceLockManager.h>

@class MBCKLock;

@interface MBCKLockManager : MBServiceLockManager {

	char _releaseLock;
	MBCKLock* _lock;

}

@property (nonatomic,retain) MBCKLock * lock;              //@synthesize lock=_lock - In the implementation block
-(char)reacquireLockWithError:(id*)arg1 ;
-(id)initWithBackupUDID:(id)arg1 delegate:(id)arg2 ;
-(void)releaseLockAsync;
-(void)startRenewingLock;
-(void)releaseLockSync;
-(void)stopRenewingLock;
-(double)renewInterval;
-(void)_scheduleTimerWithInterval:(double)arg1 ;
-(void)_releaseLockAndScheduleRetries;
-(void)_renewLockAndScheduleRetries;
-(void)resetRenewalTimer;
-(double)timeout;
-(MBCKLock *)lock;
-(void)_timerFired;
-(void)setLock:(MBCKLock *)arg1 ;
-(double)retryInterval;
@end

