/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:28 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SafariShared.framework/XPCServices/com.apple.Safari.SocialHelper.xpc/com.apple.Safari.SocialHelper
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <com.apple.Safari.SocialHelper/SocialResponseFilter.h>

@interface TwitterResponseFilter : SocialResponseFilter
-(void)filterResponse:(id)arg1 intoRecordDictionaries:(id*)arg2 recordRangeNewest:(id*)arg3 recordRangeNewestCreationDate:(id*)arg4 recordRangeOldest:(id*)arg5 recordRangeOldestCreationDate:(id*)arg6 ;
-(char)repostSuccessFromResponse:(id)arg1 ;
@end

