/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:19:16 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/UIAccessibility.framework/UIAccessibility
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIAccessibility/__NSBundleAccessibility_super.h>

@interface NSBundleAccessibility : __NSBundleAccessibility_super
+(Class)safeCategoryBaseClass;
+(id)safeCategoryTargetClassName;
-(id)localizedStringForKey:(id)arg1 value:(id)arg2 table:(id)arg3 ;
-(char)loadAndReturnError:(id*)arg1 ;
-(void)_loadAXBundleForBundleOffMainThread;
@end

