/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:13:35 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface CLDeviceMotionProperties : NSObject {

	int fMode;
	int fPowerConservation;

}

@property (assign,nonatomic) int mode; 
@property (nonatomic,readonly) int powerConservation; 
-(id)initWithMode:(int)arg1 andPowerConservation:(int)arg2 ;
-(int)powerConservation;
-(id)description;
-(void)setMode:(int)arg1 ;
-(int)mode;
@end

