/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:13:35 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreMotion/CoreMotion-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface CMGyroDataInternal : NSObject <NSCopying> {

	SCD_Struct_CM1 fRotationRate;

}
-(void)setRotationRate:(SCD_Struct_CM1)arg1 ;
-(id)initWithRotationRate:(SCD_Struct_CM1)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

