/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 4:18:54 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/AddressBook.framework/AddressBook
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface ABCCallbackInvoker : NSObject {

	/*function pointer*/void* cb;
	void* ab;
	void* context;

}
-(void)invoke;
@end

