/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:16:53 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol NSFastEnumeration
@required
-(unsigned)countByEnumeratingWithState:(SCD_Struct_IM4*)arg1 objects:(id*)arg2 count:(unsigned)arg3;

@end

