/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:30 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CloudDocsDaemon.framework/CloudDocsDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CloudDocsDaemon/BRCSharingModifyShareOperation.h>

@interface BRCSharingDestroyShareOperation : BRCSharingModifyShareOperation
-(void)main;
-(id)initWithShare:(id)arg1 zone:(id)arg2 ;
-(id)shareID;
-(unsigned long long)startActivity;
@end

