/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:03 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/PowerlogCore.framework/PowerlogCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface PLValueUtilties : NSObject
+(int)compare:(id)arg1 with:(id)arg2 ;
+(char)isNil:(id)arg1 ;
+(char)isFormater:(short)arg1 validForObject:(id)arg2 ;
+(id)formattedStringForDate:(id)arg1 ;
+(void)resetTimestampFormaterTimezone;
@end

