/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:16 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CameraKit.framework/CameraKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CameraKit/CameraKit-Structs.h>
#import <CameraKit/CMKShutterButton.h>

@interface CAMShutterButton : CMKShutterButton

@property (assign,nonatomic) int mode; 
+(id)shutterButtonWithSpec:(CAMShutterButtonSpec)arg1 ;
-(int)mode;
-(void)setMode:(int)arg1 animated:(char)arg2 ;
@end

