/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:14 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CameraKit.framework/CameraKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CameraKit/CameraKit-Structs.h>
#import <UIKit/UIView.h>

@class UILabel;

@interface CMKDisabledModeOverlayView : UIView {

	UILabel* __messageLabel;

}

@property (nonatomic,readonly) UILabel * _messageLabel;              //@synthesize _messageLabel=__messageLabel - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(UILabel *)_messageLabel;
@end

