/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:14 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CameraKit.framework/CameraKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CameraKit/CameraKit-Structs.h>
#import <CameraKit/CMKGLView.h>

@class CIFilter;

@interface CMKEffectsFullsizeView : CMKGLView {

	CIFilter* _selectedFilter;
	unsigned _selectedFilterIndex;
	unsigned _filterIndex;

}

@property (assign) unsigned filterIndex;              //@synthesize filterIndex=_filterIndex - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setFixedSize:(CGSize)arg1 ;
-(unsigned)filterIndex;
-(void)setFilterIndex:(unsigned)arg1 ;
-(void)renderPixelBuffer:(CVBufferRef)arg1 ciContext:(id)arg2 mirrorRendering:(char)arg3 ;
-(void)_layoutGLLayer;
-(void)_renderWithInputImage:(id)arg1 ciContext:(id)arg2 mirrorRendering:(char)arg3 ;
-(id)_updateSelectedFilter;
@end

