/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:16 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CameraKit.framework/CameraKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CameraKit/CMKImagePickerSpec.h>

@interface CMKPhoneImagePickerSpec : CMKImagePickerSpec
-(char)shouldCreateFlashButton;
-(char)shouldCreateElapsedTimeView;
-(char)shouldCreateFlipButton;
-(char)shouldCreateStillDuringVideo;
-(char)shouldCreateImageWell;
-(char)shouldCreateShutterButton;
-(char)shouldCreateFiltersButton;
-(char)shouldCreateModeDial;
-(char)shouldCreateHDRButton;
-(char)shouldCreatePanoramaView;
-(char)shouldCreateZoomSlider;
@end

