/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:22:09 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/GameController.framework/GameController
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <GameController/GCControllerButtonInput.h>

@class NSString;

@interface _GCControllerButtonInput : GCControllerButtonInput {

	/*^block*/id _valueChangedHandler;
	/*^block*/id _pressedChangedHandler;
	float _value;
	NSString* _descriptionName;

}
-(char)_setValue:(float)arg1 queue:(id)arg2 ;
-(/*^block*/id)valueChangedHandler;
-(void)setValueChangedHandler:(/*^block*/id)arg1 ;
-(/*^block*/id)pressedChangedHandler;
-(void)setPressedChangedHandler:(/*^block*/id)arg1 ;
-(id)initWithDescriptionName:(id)arg1 ;
-(id)description;
-(float)value;
-(char)_setValue:(float)arg1 ;
@end

