/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 5:22:09 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/GameController.framework/GameController
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class NSData;


@protocol _GCSnapshot <NSObject>
@property (nonatomic,copy) NSData * snapshotData; 
@required
-(void)setSnapshotData:(id)arg1;
-(id)initWithController:(id)arg1 snapshotData:(id)arg2;
-(NSData *)snapshotData;
-(id)initWithSnapshotData:(id)arg1;

@end

