/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:40 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusMagazineProducer.opplugin/OpusMagazineProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <OpusMagazineProducer/OpusMagazineProducer-Structs.h>
@class OKPresentation, NSMutableDictionary, OKAutoLayoutLiveFeedContext, OKAutoLayoutFreqController;

@interface OKAutoLayout : NSObject {

	OKPresentation* _presentation;
	NSMutableDictionary* _metadataCacheDict;
	OKAutoLayoutLiveFeedContext* _liveFeedContext;
	OKAutoLayoutFreqController* _freqController;
	char _allowMovieWithPhotos;
	char _forceToIterateAllLayouts;
	double _layoutAspectRatio;
	double _targetAspectRatio;

}

@property (assign,nonatomic) double layoutAspectRatio;                   //@synthesize layoutAspectRatio=_layoutAspectRatio - In the implementation block
@property (assign,nonatomic) double targetAspectRatio;                   //@synthesize targetAspectRatio=_targetAspectRatio - In the implementation block
@property (assign,nonatomic) char allowMovieWithPhotos;                  //@synthesize allowMovieWithPhotos=_allowMovieWithPhotos - In the implementation block
@property (assign,nonatomic) char forceToIterateAllLayouts;              //@synthesize forceToIterateAllLayouts=_forceToIterateAllLayouts - In the implementation block
+(float)photoScoreForMediaItem:(id)arg1 ;
+(float)croppedPercentageforRectASP:(float)arg1 photoASP:(float)arg2 ;
+(float)scaleFactorForMediaItem:(id)arg1 toFitInRect:(CGRect)arg2 ;
+(char)needsPanoramaEffectForRectASP:(float)arg1 mediaASP:(float)arg2 ;
+(float)panningCropThreshold;
-(char)allowMovieWithPhotos;
-(id)_parseLayouts:(id)arg1 ;
-(void)setLayoutAspectRatio:(double)arg1 ;
-(id)liveFeedPrimaryResolutionKey;
-(int)liveFeedNumOfPagesGenerated;
-(void)endFeed;
-(id)_metadataForMediaItem:(id)arg1 ;
-(id)_analyzeLayouts2:(id)arg1 ;
-(char)forceToIterateAllLayouts;
-(void)setAllowMovieWithPhotos:(char)arg1 ;
-(double)_croppingScoreForMediaItems:(id)arg1 layoutInfo:(id)arg2 ;
-(id)_matchMediaItems:(id)arg1 toLayoutInfo:(id)arg2 orderedKeys:(id)arg3 ;
-(int)liveFeedNumOfMediasUsed;
-(double)_maxDurationOfMediaItems:(id)arg1 ;
-(void)setForceToIterateAllLayouts:(char)arg1 ;
-(double)targetAspectRatio;
-(id)_titleGuidelineFromPresentation:(id)arg1 ;
-(char)startFeedWith:(id)arg1 primaryResolutionKey:(id)arg2 ;
-(double)layoutAspectRatio;
-(unsigned)_analyzeLayouts:(id)arg1 ;
-(id)generatePagesByMediaItems:(id)arg1 layoutsByResolution:(id)arg2 primaryResolutionKey:(id)arg3 ;
-(id)_subtitleGuidelineFromPresentation:(id)arg1 forMediaItem:(id)arg2 ;
-(void)setTargetAspectRatio:(double)arg1 ;
-(id)_findBestMatchingLayoutFromLayouts:(id)arg1 forMediaItems:(id)arg2 currentIndx:(unsigned)arg3 checkFollowingMediaItems:(int)arg4 remainingItems:(unsigned)arg5 guidelineForMediaItems:(id)arg6 isFirstPage:(char)arg7 ;
-(id)_loopAllLayouts:(id)arg1 numOfAllMedias:(unsigned)arg2 layoutInfos:(id)arg3 primaryResolution:(id)arg4 ;
-(id)generateNextPagesByMediaItems:(id)arg1 maxPages:(int)arg2 isFirstPage:(char)arg3 ;
-(void)dealloc;
-(id)initWithPresentation:(id)arg1 ;
@end

