/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:40 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/PlugIns/OpusMagazineProducer.opplugin/OpusMagazineProducer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface OKAutoLayoutGrid : NSObject {

	int* _tiles;
	unsigned _rows;
	unsigned _columns;

}

@property (readonly) unsigned rows;                 //@synthesize rows=_rows - In the implementation block
@property (readonly) unsigned columns;              //@synthesize columns=_columns - In the implementation block
-(id)nextPossibleRects:(char)arg1 ;
-(id)initWithRows:(unsigned)arg1 columns:(unsigned)arg2 ;
-(char)hasAnyEmptyTiles;
-(char)nextEmptyTile:(unsigned*)arg1 :(unsigned*)arg2 ;
-(void)unmarkForAreaX:(unsigned)arg1 Y:(unsigned)arg2 W:(unsigned)arg3 H:(unsigned)arg4 ;
-(char)biggestEmptyRectFromPtX:(unsigned)arg1 Y:(unsigned)arg2 W:(unsigned*)arg3 H:(unsigned*)arg4 ;
-(void)mark:(unsigned)arg1 forAreaX:(unsigned)arg2 Y:(unsigned)arg3 W:(unsigned)arg4 H:(unsigned)arg5 ;
-(void)dealloc;
-(id)description;
-(void)reset;
-(unsigned)rows;
-(unsigned)columns;
@end

