/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:35:11 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/ModelIO.framework/ModelIO
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol NSFastEnumeration
@required
-(unsigned)countByEnumeratingWithState:(SCD_Struct_MD4*)arg1 objects:(id*)arg2 count:(unsigned)arg3;

@end

