/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:20 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CameraUI.framework/CameraUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol CAMIrisRequest <NSObject>
@required
-(id)irisLocalVideoDestinationURLForHDREV0:(char)arg1;
-(id)irisStillImagePersistenceUUIDForHDREV0:(char)arg1;
-(id)irisVideoPersistenceUUIDForHDREV0:(char)arg1;
-(char)isHDREV0LocalVideoDestinationURL:(id)arg1;
-(id)irisIdentifierForHDREV0:(char)arg1;

@end

