/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:01 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AssetsLibraryServices/AssetsLibraryServices-Structs.h>
@interface PLSecurity : NSObject
+(char)canSkipUserPromptsForProcessWithName:(id)arg1 identifier:(int)arg2 ;
+(char)connectionIsEntitledForPhotoKit:(id)arg1 ;
+(char)isEntitledForPhotoKit;
+(char)secTask:(SecTaskRef)arg1 hasEntitlement:(id)arg2 ;
+(char)connection:(id)arg1 hasEntitlement:(id)arg2 ;
+(char)isEntitledForCloudSharingData;
@end

