/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:16:05 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/FMFUI.framework/FMFUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSTableCell.h>

@interface FollowerDetailsLinkCell : PSTableCell
+(int)cellStyle;
-(void)refreshCellContentsWithSpecifier:(id)arg1 ;
@end

