/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:46 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/PairedSync.framework/Support/pairedsyncd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PSDSchedulingObserver <NSObject>
@required
-(void)scheduler:(id)arg1 didStartSessionWithActivityCount:(unsigned)arg2 isResuming:(char)arg3;
-(void)scheduler:(id)arg1 didStartActivity:(id)arg2;
-(void)scheduler:(id)arg1 activityDidCompleteSending:(id)arg2;
-(void)scheduler:(id)arg1 didFinishActivity:(id)arg2 success:(char)arg3 error:(id)arg4;
-(void)schedulerDidFinishSession:(id)arg1;

@end

