/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 4:44:51 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/CoreAudioKit.framework/CoreAudioKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol AUAudioUnitRemoteViewProtocol <AUAudioUnitViewProtocol>
@required
-(void)connectToContextWithSessionID:(id)arg1 withCompletion:(/*^block*/id)arg2;

@end

