/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:19:10 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/callservicesd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol CSDIDSMessengerDelegate;
@interface CSDIDSMessenger : NSObject {

	id<CSDIDSMessengerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<CSDIDSMessengerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)setDelegate:(id<CSDIDSMessengerDelegate>)arg1 ;
-(id<CSDIDSMessengerDelegate>)delegate;
-(void)sendMessage:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
@end

