/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 4:19:35 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AddressBookUI/ABMultiCellContentView_Simple.h>

@class UIButton;

@interface ABMultiCellContentView_RelatedName : ABMultiCellContentView_Simple {

	UIButton* _accessoryButton;

}

@property (nonatomic,readonly) UIButton * accessoryButton;              //@synthesize accessoryButton=_accessoryButton - In the implementation block
+(void)setupRelatedNamesView:(id)arg1 withStyleProvider:(id)arg2 ;
-(UIButton *)accessoryButton;
-(void)dealloc;
-(void)setName:(id)arg1 ;
@end

