/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 4:19:35 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AddressBookUI/ABMultiCellContentView_DisplayAlternate.h>

@interface ABMultiCellContentView_IM : ABMultiCellContentView_DisplayAlternate
+(unsigned)rowsForPropertyGroup:(id)arg1 info:(id)arg2 ;
-(void)reloadFromModel;
-(void)reloadFromModelIncludingRows:(char)arg1 ;
-(id)pickerView;
-(void)textFieldTextDidChange:(id)arg1 ;
@end

