/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 4:19:36 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ABPersonLinkingUIDelegate
@required
-(char)shouldAllowLinkingAnotherContact;
-(int)numberOfLinkedCardRows;
-(id)sourceNameForCardAtRow:(int)arg1;
-(id)personNameForCardAtRow:(int)arg1;
-(char)manuallyUnlinkCardAtRow:(int)arg1;
-(char)canUnlinkCardAtRow:(int)arg1;
-(char)manuallyLinkPerson:(id)arg1;
-(char)shouldAllowLinkingPersonWithRecordID:(int)arg1;
-(id)newPersonViewControllerForLinkedCardAtRow:(int)arg1;
-(id)newPeoplePickerForLinking;

@end

