/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:14:52 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AirPortAssistant/StepByStepUIViewController.h>
#import <libobjc.A.dylib/TableViewManagerDelegate.h>

@interface StepByStepUIViewController_ReplaceChoice : StepByStepUIViewController <TableViewManagerDelegate>
-(void)loadView;
-(void)viewWillAppear:(char)arg1 ;
-(void)touchInCellAtIndexPath:(id)arg1 ;
-(void)setupTable;
@end

