/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:33 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SFCompanionServiceManagerClient <NSObject>
@required
-(void)streamToService:(id)arg1 withFileHandle:(id)arg2 acceptReply:(/*^block*/id)arg3;

@end

