/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:20 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/RemoteUI.framework/RemoteUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <RemoteUI/RUIElement.h>

@class NSString, NSURL;

@interface RUIFooterElement : RUIElement {

	NSString* _text;
	NSURL* _linkURL;

}

@property (nonatomic,copy) NSString * text;              //@synthesize text=_text - In the implementation block
@property (nonatomic,copy) NSURL * linkURL;              //@synthesize linkURL=_linkURL - In the implementation block
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
-(NSURL *)linkURL;
-(void)setLinkURL:(NSURL *)arg1 ;
-(void)configureView:(id)arg1 ;
@end

