/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:22 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SAObjects/SABaseClientBoundCommand.h>

@class NSArray, NSString;

@interface SAAceDomainSignal : SABaseClientBoundCommand

@property (nonatomic,copy) NSArray * appIdHints; 
@property (nonatomic,copy) NSString * domain; 
+(id)aceDomainSignal;
+(id)aceDomainSignalWithDictionary:(id)arg1 context:(id)arg2 ;
-(char)ad_commandCausesPunchout;
-(void)_ad_handleAceDomainSignalRequest:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(id)_ad_likelyApplicationBundleIdentifiers;
-(void)setDomain:(NSString *)arg1 ;
-(NSString *)domain;
-(id)groupIdentifier;
-(id)encodedClassName;
-(char)requiresResponse;
-(NSArray *)appIdHints;
-(void)setAppIdHints:(NSArray *)arg1 ;
@end

