/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:18:24 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SAObjects/AceObject.h>
#import <libobjc.A.dylib/AFSessionObject.h>
#import <SAObjects/SAAceSerializable.h>
#import <SAObjects/SAAceCommand.h>

@class NSString;

@interface SABaseCommand : AceObject <AFSessionObject, SAAceSerializable, SAAceCommand>

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy) NSString * aceId; 
@property (nonatomic,copy) NSString * refId; 
+(void)resultWithServiceHelper:(id)arg1 command:(id)arg2 description:(id)arg3 reply:(/*^block*/id)arg4 ;
+(id)newAceObjectWithDictionaryWithCustomHandling:(id)arg1 context:(id)arg2 ;
+(id)baseCommand;
+(id)baseCommandWithDictionary:(id)arg1 context:(id)arg2 ;
-(char)ad_hasCallbacks;
-(int)resultCallbackCode;
-(char)_ad_isRetryableCommand;
-(id)serializedAceDataError:(id*)arg1 ;
-(char)af_bufferingAllowedDuringActiveSession;
-(void)af_logDiagnostics;
-(id)groupIdentifier;
-(id)encodedClassName;
-(NSString *)aceId;
-(void)setAceId:(NSString *)arg1 ;
-(NSString *)refId;
-(void)setRefId:(NSString *)arg1 ;
@end

