/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:47:36 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/Social.framework/Social
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class NSString;

@interface SLFacebookAlbumTableViewCell : UITableViewCell {

	NSString* _albumIdentifier;

}

@property (retain) NSString * albumIdentifier;              //@synthesize albumIdentifier=_albumIdentifier - In the implementation block
-(void)setAlbumIdentifier:(NSString *)arg1 ;
-(NSString *)albumIdentifier;
@end

