/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:47:36 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/Social.framework/Social
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface SLYahooWebAuthRequest : NSObject
+(id)urlForClientID:(id)arg1 redirectURI:(id)arg2 username:(id)arg3 ;
+(id)requestForURL:(id)arg1 ;
+(void)clearCookiesFromStorage:(id)arg1 ;
+(id)urlRequestForClientID:(id)arg1 redirectURI:(id)arg2 username:(id)arg3 ;
+(char)urlPageWillContainAuthorizationCode:(id)arg1 ;
+(id)authCodeFromURLRequest:(id)arg1 ;
@end

