/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:42 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CoreCDPUI.framework/CoreCDPUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol KeychainSyncViewControllerDelegate <NSObject>
@optional
-(void)keychainSyncControllerCancel:(id)arg1;

@required
-(void)keychainSyncController:(id)arg1 didFinishWithResult:(id)arg2 error:(id)arg3;

@end

