/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:24 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/CertInfo.framework/CertInfo
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol CertInfoTrustDescription <NSObject>
@required
-(unsigned)certificateCount;
-(id)certificatePropertiesAtIndex:(unsigned)arg1;
-(id)summaryTitle;
-(id)summarySubtitle;
-(id)summaryDescriptionItems;
-(id)certificateSubjectSummaryAtIndex:(unsigned)arg1;
-(id)certificateIssuerSummaryAtIndex:(unsigned)arg1;
-(id)certificateExpirationDateAtIndex:(unsigned)arg1;
-(char)isRootCertificate;
-(char)isTrusted;

@end

