/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 4:46:14 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreFoundation/CoreFoundation-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSMutableCopying.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@interface NSData : NSObject <NSCopying, NSMutableCopying, NSSecureCoding>

@property (readonly) unsigned length; 
@property (readonly) const void* bytes; 
+(char)_base64DecodingAlwaysSucceedsForOptions:(unsigned)arg1 ;
+(id)dataWithContentsOfMappedFile:(id)arg1 ;
+(id)dataWithContentsOfURL:(id)arg1 options:(unsigned)arg2 error:(id*)arg3 ;
+(id)allocWithZone:(NSZone*)arg1 ;
+(id)dataWithBytes:(const void*)arg1 length:(unsigned)arg2 ;
+(char)supportsSecureCoding;
+(id)data;
+(id)dataWithContentsOfFile:(id)arg1 ;
+(id)dataWithBytesNoCopy:(void*)arg1 length:(unsigned)arg2 ;
+(id)dataWithContentsOfFile:(id)arg1 options:(unsigned)arg2 error:(id*)arg3 ;
+(id)dataWithBytesNoCopy:(void*)arg1 length:(unsigned)arg2 freeWhenDone:(char)arg3 ;
+(id)dataWithContentsOfURL:(id)arg1 ;
+(id)dataWithData:(id)arg1 ;
-(id)replacementObjectForPortCoder:(id)arg1 ;
-(id)_web_guessedMIMETypeForXML;
-(id)_web_guessedMIMEType;
-(id)_web_guessedMIMETypeForExtension:(id)arg1 ;
-(id)_web_parseRFC822HeaderFields;
-(id)_replaceCString:(const char*)arg1 withCString:(const char*)arg2 ;
-(char)isNSData__;
-(id)replacementObjectForCoder:(id)arg1 ;
-(unsigned long)_cfTypeID;
-(id)initWithBytes:(void*)arg1 length:(unsigned)arg2 copy:(char)arg3 deallocator:(/*^block*/id)arg4 ;
-(char)_isDispatchData;
-(id)initWithBytes:(void*)arg1 length:(unsigned)arg2 copy:(char)arg3 freeWhenDone:(char)arg4 bytesAreVM:(char)arg5 ;
-(char)_canReplaceWithDispatchDataForXPCCoder;
-(char)_isCompactAndReturnBytes:(const void*)arg1 ;
-(char)_isCompact;
-(char)_copyWillRetain;
-(id)initWithContentsOfMappedFile:(id)arg1 ;
-(NSRange)rangeOfData:(id)arg1 options:(unsigned)arg2 range:(NSRange)arg3 ;
-(char)_decodeBase64EncodedCharacterBuffer:(const char*)arg1 length:(unsigned)arg2 options:(unsigned)arg3 buffer:(char*)arg4 bufferLength:(unsigned)arg5 state:(SCD_Struct_NS12*)arg6 ;
-(id)_initWithBase64EncodedObject:(id)arg1 options:(unsigned)arg2 ;
-(id)_base64EncodingAsString:(char)arg1 withOptions:(unsigned)arg2 ;
-(id)_asciiDescription;
-(char)_allowsDirectEncoding;
-(void)getBytes:(void*)arg1 ;
-(char)writeToFile:(id)arg1 atomically:(char)arg2 error:(id*)arg3 ;
-(id)initWithContentsOfMappedFile:(id)arg1 error:(id*)arg2 ;
-(id)initWithContentsOfFile:(id)arg1 error:(id*)arg2 ;
-(id)_createDispatchData;
-(id)base64EncodedDataWithOptions:(unsigned)arg1 ;
-(id)initWithBase64Encoding:(id)arg1 ;
-(id)base64Encoding;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(unsigned)length;
-(char)writeToFile:(id)arg1 atomically:(char)arg2 ;
-(char)writeToURL:(id)arg1 options:(unsigned)arg2 error:(id*)arg3 ;
-(char)writeToURL:(id)arg1 atomically:(char)arg2 ;
-(const void*)bytes;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)getBytes:(void*)arg1 length:(unsigned)arg2 ;
-(Class)classForCoder;
-(id)initWithContentsOfFile:(id)arg1 ;
-(id)initWithData:(id)arg1 ;
-(char)writeToFile:(id)arg1 options:(unsigned)arg2 error:(id*)arg3 ;
-(id)base64EncodedStringWithOptions:(unsigned)arg1 ;
-(id)initWithBase64EncodedString:(id)arg1 options:(unsigned)arg2 ;
-(id)initWithContentsOfFile:(id)arg1 options:(unsigned)arg2 error:(id*)arg3 ;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(id)initWithBytes:(const void*)arg1 length:(unsigned)arg2 ;
-(id)initWithContentsOfURL:(id)arg1 ;
-(void)getBytes:(void*)arg1 range:(NSRange)arg2 ;
-(void)enumerateByteRangesUsingBlock:(/*^block*/id)arg1 ;
-(char)isEqualToData:(id)arg1 ;
-(id)initWithContentsOfURL:(id)arg1 options:(unsigned)arg2 error:(id*)arg3 ;
-(id)initWithBase64EncodedData:(id)arg1 options:(unsigned)arg2 ;
-(id)initWithBytesNoCopy:(void*)arg1 length:(unsigned)arg2 freeWhenDone:(char)arg3 ;
-(id)initWithBytesNoCopy:(void*)arg1 length:(unsigned)arg2 ;
-(id)subdataWithRange:(NSRange)arg1 ;
-(id)initWithBytesNoCopy:(void*)arg1 length:(unsigned)arg2 deallocator:(/*^block*/id)arg3 ;
-(char)_isSafeResumeDataForBackgroundDownload;
@end

