/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:16:48 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/IAP.framework/Support/iapd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSTimer;

@interface IAPMicrophoneEventHandlerHelper : NSObject {

	NSTimer* _stateChangeDebouceTimer;

}
+(id)sharedInstance;
-(void)microphoneStateChangedNotification;
-(void)microphoneStateChangeDebouceTimeout;
-(void)sendMicrophoneStateChangedNotification;
-(void)dealloc;
@end

