/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:47 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PassKitCore/PassKitCore-Structs.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@interface PKPaymentDeviceConfigurationData : NSObject <NSSecureCoding> {

	char _devSigned;

}

@property (assign,nonatomic) char devSigned;              //@synthesize devSigned=_devSigned - In the implementation block
+(char)supportsSecureCoding;
-(char)devSigned;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setDevSigned:(char)arg1 ;
@end

