/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 4:16:01 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AVFoundation/AVFoundation-Structs.h>
@interface AVCaptureFileOutputInternal : NSObject {

	SCD_Struct_CM5 maxRecordedDuration;
	long long maxRecordedFileSize;
	long long minFreeDiskSpaceLimit;
	char pausesRecordingOnInterruption;

}
-(id)init;
@end

