/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:01 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/MPUFoundation.framework/MPUFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MPUActionTableViewDataSource <UITableViewDataSource>
@required
+(id)actionCellConfigurationClasses;
+(id)actionCellConfigurationClassesForLocation:(unsigned)arg1;
-(void)reloadActionRowsAnimated:(char)arg1;
-(Class)cellConfigurationForIndexPath:(id)arg1;
-(int)numberOfTopActionRowsInTableView:(id)arg1;
-(int)numberOfBottomActionRowsInTableView:(id)arg1;
-(char)shouldShowActionCellConfiguration:(Class)arg1;
-(int)numberOfActionRowsInTableView:(id)arg1;

@end

