/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:17:01 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/MPUFoundation.framework/MPUFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MediaPlayer/MPAVController.h>

@class MPUAVPlaylistManager;

@interface MPUAVPlayer : MPAVController

@property (getter=_playlistManager,nonatomic,retain) MPUAVPlaylistManager * playlistManager; 
+(Class)playlistManagerClass;
-(id)_playlistManager;
@end

