/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:24 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol CKFeedCollectionViewLayoutDatasource <NSObject>
@required
-(unsigned)numberOfSectionsInFeedLayout:(id)arg1;
-(unsigned)numberOfItemsInSection:(unsigned)arg1 forFeedLayout:(id)arg2;

@end

