/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:25 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIAlertView.h>

@interface CKMessageAlertSheet : UIAlertView {

	char _showingTagline;

}

@property (assign,nonatomic) char showingTagline;              //@synthesize showingTagline=_showingTagline - In the implementation block
-(void)layoutAnimated:(char)arg1 ;
-(void)updateTagline;
-(char)showingTagline;
-(void)setShowingTagline:(char)arg1 ;
@end

