/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 10:15:26 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ChatKit/CKMessagePartChatItem.h>

@class NSAttributedString;

@interface CKTextMessagePartChatItem : CKMessagePartChatItem

@property (nonatomic,copy,readonly) NSAttributedString * text; 
@property (nonatomic,copy,readonly) NSAttributedString * subject; 
@property (nonatomic,readonly) char containsHyperlink; 
-(NSAttributedString *)text;
-(NSAttributedString *)subject;
-(id)loadTranscriptText;
-(Class)balloonViewClass;
-(id)composition;
-(id)pasteboardItems;
-(char)containsHyperlink;
-(id)_time;
@end

