/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:36:07 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol NEFilterExtensionProviderProtocol <NEExtensionProviderProtocol>
@required
-(void)setExtensionIdentifier:(id)arg1 deviceIdentifier:(id)arg2;
-(void)updateConfiguration:(id)arg1;
-(void)startFilterWithOptions:(id)arg1 completionHandler:(/*^block*/id)arg2;

@end

