/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:36:08 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <NetworkExtension/NEVPNProtocol.h>

@class NSString;

@interface NEVPNProtocolPlugin : NEVPNProtocol {

	NSString* _pluginType;

}

@property (readonly) NSString * pluginType;              //@synthesize pluginType=_pluginType - In the implementation block
-(NSString *)pluginType;
@end

