/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, November 18, 2015 at 6:51:37 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/Frameworks/WebKit.framework/WebKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <WebKit/WKDOMNode.h>

@class NSString;

@interface WKDOMElement : WKDOMNode

@property (readonly) NSString * tagName; 
-(char)hasAttribute:(id)arg1 ;
-(void)setAttribute:(id)arg1 value:(id)arg2 ;
-(NSString *)tagName;
-(id)getAttribute:(id)arg1 ;
@end

